### ISSUE TITLE
[dev.icinga.com #9059] Can't initiate an ascending sort by host or service severity

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1606]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9059

**Created by jmeyer on 2015-04-14 11:19:14 +00:00**

Assignee: _elippmann_
Status: _Resolved_  (closed on _2015-05-21 10:25:04 +00:00_)
Target Version: _2.0.0-rc1_
Last Update: _2015-05-21 10:25:04 +00:00 (in Redmine)_

---

Descending is hardcoded in DataView\\HostStatus and DataView\\ServiceStatus.

**Changesets**

_2015-05-13 15:48:34 +00:00_ by _aklimov_ 7e1f9f6dccc1085bc1066e6152e548d854050fac

    Make ascending sort by host or service severity initiatable
    
    fixes #9059

_2015-05-15 09:19:52 +00:00_ by _aklimov_ 386d4db851aed056652d892d539de35b403c5062

    Make ascending sort by host or service severity initiatable
    
    fixes #9059

_2015-05-21 10:20:18 +00:00_ by _elippmann_ 82f9425b904f8567b373b56056669c32806fa6af

    Revert "Make ascending sort by host or service severity initiatable"
    
    This reverts commit 386d4db851aed056652d892d539de35b403c5062.
    
    The commit introduced the bug that changing the sort direction no longer changed the sort direction :)
    
    refs #9059

_2015-05-21 10:20:18 +00:00_ by _elippmann_ 195275a716be571bb2c94cf868c3f7364fe0ecfb

    monitoring: Don't hardcode sort direction of the severity columns
    
    fixes #9059

---

**Relations**:

* duplicates [#9059](https://dev.icinga.com/issues/9059)

**Comment by Fonata** [comment]
I have a general usage question: where does one set the severity of a service?

**Comment by lazyfrosch** [comment]
@Fonata please do not comment to a very old issue.

Severity is calculated from Icinga Status information in the IDO, so that we can sort criticality.

It is inside a SQL query currently: https://github.com/Icinga/icingaweb2/blob/c547f4c17f20bae02a12848c12b59804e6c73f7a/modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatusQuery.php#L104

Please open a new issue if you have problems or further questions
