### ISSUE TITLE
[dev.icinga.com #9629] Set default dashboard for all users

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1830]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9629

**Created by elippmann on 2015-07-15 09:31:44 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2017-01-10 18:11:38 +00:00 (in Redmine)_

---

---

**Relations**:

* duplicates [#9629](https://dev.icinga.com/issues/9629)
* duplicates [#9629](https://dev.icinga.com/issues/9629)

**Comment by cbnorman** [comment]
is there a time frame to implement this feature?

**Comment by Thomas-Gelf** [comment]
@cbnorman: as far as I know: sorry, no. @lippserd: anything new on this? If a specific dashboard for all users is all you need, you might want to give my [enforceddashboard](https://github.com/Thomas-Gelf/icingaweb2-module-enforceddashboard) module a look. However, that one is very strict and opinionated - and does no longer allow users to have their custom Dashboard.

Problem here is that while allowing to "Set a default dashboard for all users" might be easy, the whole context of sharing Dashboards, group permissions, combinations of all those and so on is what makes this feature complicated. We started work on this long time ago, it grew from a small idea to a feature-rich monster - and failed.

This would be an important feature to many people, just: we would have to restart from scratch and completely redesign it. Keeping in mind the lectures we learned during the first attempt. Just, as there are always more important tasks and this is a boring one where you could easily hurt yourself, no one is showing up declaring "I have the immediate desire to implement this!". We usually try to find one (or multiple) sponsors for features like this, as money always helps to speed things up - but as far as I know there is currently no one in sight for this feature.

@lippserd mentioned a potential sponsor nearly a year ago. As far as I remember that project never really started. By the end the customer found it's own workaround and decided to wait unless the full-blown solution shows up for free. Doing so absolutely makes sense, as like he correctly said "This is an essential feature, so sooner or later it will show up anyways". Turned out that this is going to be kind of "later" :laughing:

Cheers,
Thomas

**Comment by cbnorman** [comment]
hi @Thomas-Gelf thanks for the detailed response. id like to avoid restricting users from creating the own custom dashboards as that one of the nice benefits to icingaweb2 over our previous system. i have briefly looked at how dashboards are configured and found that i could copy my custom ones from /etc/icingaweb2/dashboards/cnorman/dashboard.ini to /etc/icingaweb2/dashboards/<user>/dashboard.ini and they would show correctly for that particular user. wouldnt it be doable to just have icingaweb2 check the root of dashboards and add any found there?

thanks for you help.

**Comment by cbnorman** [comment]
any thoughts on my idea here?

**Comment by matthenning** [comment]
@cbnorman Have you found a solution yet? When a new user logs in the default dashboard.ini is created anyway as far as I know, so it could be as simple as checking for a dashboard.default.ini in /etc/icingaweb2/dashboards for example and copy it to the new directory.

**Comment by Duffkess** [comment]
As I read through all of this I agree with everything.. But still I need a workaround, dirty and quick.. so What do I do? I just say:
Script, Crond, LDAPSearch, Copy'n'Paste..

**Comment by wols** [comment]
Hi, my current workaround:
```
/etc/icingaweb2/dashboards/
├── default
│   └── dashboard.ini
├── user1
│   └── dashboard.ini -> ../default/dashboard.ini
├── user2
│   └── dashboard.ini -> ../default/dashboard.ini
├── user3
│   └── dashboard.ini -> ../default/dashboard.ini
```
I have createt a default dashboard (as userX) and copied it to `default` as root.
Now you can add a link - manual or via cron job - for every (new) user.
The file rights protect against overwriting by the respective user.

**Comment by nilmerg** [comment]
Continues with #3809. Closed.
