### ISSUE TITLE
[dev.icinga.com #11160] Please align URL capabilities to filters

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2296]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11160

**Created by tgelf on 2016-02-15 11:31:39 +00:00**

Assignee: _(none)_
Status: _Feedback_ 
Target Version: _Backlog_
Last Update: _2016-12-22 15:44:00 +00:00 (in Redmine)_

---

We introduced technical debt by implementing filter capabilities with no matching URL rendering rules. We must bring our filters back to a state where all of them can be rendered to and parsed from URL strings. We should also take care that most of our data providers using filters are able to render/understand all filter capabilities.

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment]
Interesting, thanks. So now that we can track that proposal in a dedicated issue, may I ask for the state of the of the original request? :tongue:

**Comment by lippserd** [comment]
Nothing happened I guess :)

**Comment by Al2Klimov** [comment]
Suggestion:

* `a*=b`: case insensitive modifier for match
* `a~=b`: equal instead of match
* `a*~=b`: case insensitive equal
* `a!*=b`: case insensitive modifier for not match
* `a!~=b`: not equal instead of not match
* `a!*~=b`: case insensitive not equal

Additional ideas:

* `a>(b|c|d)` and any other operator in addition to `a=(b|c|d)`
* `a=(b&c&d)` in addition to `a=(b|c|d)`

**Comment by nilmerg** [comment]
Since nothing happened after soon 5 years, we can forget about this I think. Though, it's not only that nothing has happened:

* Anyone using `FilterMatch` directly did this with an *equal* comparison in mind, as that's also what's being used for `Filter::expression('foo', '=', 'bar')`, so `FilterEqual` is the alien here and is completely redundant.
* Case insensitive filters were never meant to be rendered back to a string representation, as that would allow the end user define the case sensitivity. Now think about allowing the user to perform a case insensitive search over customvars or plugin output, without having an index reflecting the necessary collation. (Not mentioning the necessity to know prior performing a query which column even supports case insensitivity.)
* Array matching didn't broke with the mentioned commit. Maybe another commit broke `(foo|ba*)`, or it never has worked. Supporting this for any backend would also be difficult if not impossible.

And since I'm about to implement an alternative to `Icinga\Data\Filter` in the ipl, which still uses the very same string representation, this case can be closed once and for all.
