### ISSUE TITLE
[dev.icinga.com #11609] Ability to prevent concurrent sessions for user accounts

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2394]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11609

**Created by ClemensBW on 2016-04-18 12:28:03 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-10-04 09:42:35 +00:00 (in Redmine)_

---

A second application with the same user account must be prevented.
Alternatively, however, the second notification will be admitted; in which case the original session must be ended. This variant may be useful to prevent a user account is temporarily blocked, eg. by closing or browser crash without prior Logout.

It is recommended that the web application shows the user a warning message when they log on to a webapplication, but at the same time a session for his account is already active. This increases the likelihood that attacks on accounts are discovered.

However, there are web applications that provide explicit access through various channels (browser1, browser2 or mobile devices) or must allow for other imperative reasons multiple registrations. In such cases, it may have to be possible that a plurality of parallel sessions are opened.
Motivation: If multiple sessions are simultaneously active for a user account, which may mean that the account is used by different users at the same time or that this is a test attack.

**Comment by leeclemens** [comment]
I'm not sure this makes sense, unless there is a functional issue with the same user having two sessions (two browsers tabs) open concurrently...thinking mid-air collision issues while updating (e.g. adding downtimes), but database level locking/unique keys should mitigate much of that

**Comment by bb-Ricardo** [comment]
This is about a attack vector. If you are in the same browser (with different tabs) you still have the same session. If someone connects from a different host with your credentials then it could be an attack to your user account.

**Comment by Thomas-Gelf** [comment]
First of all, I believe that a discussion whether or not this makes sense leads nowhere. While some consider similar mechanisms a stupid and nasty thing, it might be an important security feature for others.

So, providing this would be nice as long as you can turn it on or off, fitting your requirements. To get this implemented we should:

* provide it in a configurable way:
  * whether to allow concurrent sessions or not (see above)
  * whether to allow a session to switch IP (some people consider this a clear indication for a hack, others already realized that roaming is a thing)
  * eventually provide hooks allowing custom modules to hook in more custom logic, like "Allow roaming and multiple sessions, but only within a single country"
* kick out an existing session when a new one starts, telling the former user the reason for doing so
* or should we tell the new session that there is an existing one, asking the user whether or not it should be terminated? For this and similar questions: read on.

Problem with all implementations: when you try to make it convenient, it will be convenient either for you or for the attacker. And you have no chance to figure out who is who. Did the good guy log in first or the bad guy? Should we provide additional information (that there was a session that has been terminated, new and or former IP address) on every session collision, and if so - to whom? Those questions must be addressed. And there will be no best answer to some of those questions.

All this requires us to have "a list" of active sessions, an information usually not available to us for security reasons (no read access to the session directory, just to the files in there. We'll not shoot ourselves in the head by introducing DB-based sessions. Don't get me wrong on this, I'm a big big fan of relational databases, but a session store is not what they have been built for. However, there are ongoing plans to make Redis an optional first-class citizen for sessions and similar tasks in an Icinga environment. That will allow us to give admins access to a list of logged in users, might be the base for future chat-like additions and would help us with this feature.

As soon as we have such a session backend, this feature can easily be implemented.

Cheers,
Thomas

**Comment by leeclemens** [comment]
I don't consider it a stupid or nasty thing.

If someone connects from another machine successfully with your credentials, they have already been lost. Tabs was a bad example, multiple browsers or using VMs would be more likely usecases.

There are a lot of caveats to mitigation attempts for this (which @Thomas-Gelf has layed out very well), I merely wanted to note there are potential issues here, particularly when language such as "must be prevented" is used in the OP.

**Comment by bb-Ricardo** [comment]
Hello @Thomas-Gelf,

first thanks for your thoughts you put into this and your lengthly answer.

here is what I would propose:
* Attacker/User logs in with second session (Limit is always only 1 session at one time)
** if the second login occurs tell both parties the details.
** the last logged in session keeps the session
** both parties (former and current session holders) get told what happend including details (IP, time stamp)
** Yes the attacker knows that he/she just stole a session. I still try to think whats the gain in this information

* Session handling
** if this would be implemented then only one a session limit of 1 mould make sense.
** more then one (lets say 2) session would defeat the purpose

The question I don't know in this context ist: Is the user table read on every request from the db or is it cached on the web server?

If the table is getting queried on every request then you would be forced to save following informations to the user record:
* old session ID
* current session ID
* current IP address

* On session init the current session ID will be saved as old and current session ID and IP address will be saved instead. Also inform the user about the old IP address
* If on page reload the user submitted session ID equals the old session ID from the user table then invalidate the session tell the user the session expired for $reason and submit the IP address as well.

If the user information is cached on the web server then it gets more difficult to let the "old" user know what just happened.

What do you think about it?

Cheers
Ricardo

**Comment by Thomas-Gelf** [comment]
> Yes the attacker knows that he/she just stole a session

But we shouldn't tell him where the original user came from. As we have no chance to figure out which one of those two is the bad guy, we should only tell both THAT such an event occurred and that more details are to be found in the server log. Showing no IP/Browser/Session/whatever details to any of the parties.

> Is the user table read on every request from the db or is it cached on the web server?

Neither. We do not want to go to the database at all for every single request (at least not for those not asking for other information like monitoring data). And using a relational database as a session store is an absolute no-go. Even files are tricky, many frameworks stumble upon very basic issues like file-locking with the default PHP session backend. We try hard to avoid those pitfalls and to keep the base framework as fast as possible.

> [..] What do you think about it?

Please re-read my above comment, especially the last paragraph. Most of your questions should be already be answered. At least indirectly :laughing: - so let me be more concrete:

* currently we use PHP's own session storage and (intentionally) do not care about it's details
* this way most people use file-based sessions while others might use Redis, Memcached or similar
* for security reasons PHP session storage does not allow one to "get a list of authenticated users"
* even if we would ask PHP for related details, secure installations would not even allow the web server to list the session directory content at file-system level
* we are not going to replicate session information to the db. It's a no-brainer performance-wise - and many installations use other authentication methods and do not even use the Icinga Web 2 DB

Said all this: no way to implement this feature right now. But we will be able to do so in the future. There are very concrete plans to make Redis an optional but first-class citizen in Icinga environments, and various prototypes are using it for one reason or the other. And that's why I concluded my above comment with:

> As soon as we have such a session backend, this feature can easily be implemented.

Until then, this feature-request probably remains pending. And it will always be opt-in (eventually per user/group/role) and not the default behavior. There too many scenarios where parallel logins of the same user are desirable.

If you have urgent need for this please note that User Backends are hooks in recent versions of Icinga Web 2. So you could easily provide such functionality in a custom module in an upgrade-safe way, fitting your specific environment. Configure your PHP to put session files to a directory allowing the web server to list it's content, scan all files on login (or keep a separate custom user/sid index in case you have many users) - and remove the former session file when a user logs in again. No need to duplicate authentication logic, you could probably just inherit from an existing class. There is no hook allowing you to specify a "logout message" for the former sessions, but I guess that's something one could live with.

Cheers,
Thomas

**Comment by lippserd** [comment]
I close this as wontfix as we won't implement this feature until someone sponsors it.
