### ISSUE TITLE
[dev.icinga.com #12640] MSSQL ressource not working

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2545]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12640

**Created by hroc on 2016-09-05 08:28:26 +00:00**

Assignee: _hroc_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-10-06 07:38:58 +00:00 (in Redmine)_

---

"Connection failed PDO::\_\_construct(): SQLSTATE\[IM001\]: Driver does not support this function: driver does not support setting attributes"

OS: Debian 8 / Freetds 0.91-6

other people are reporting the same problem on the forums:

https://monitoring-portal.org/index.php?thread/36062-mssql-datenbanken-als-importquelle/

**Attachments**

* [icingaweb2_mssql-error.JPG](https://dev.icinga.com/attachments/download/3619/icingaweb2_mssql-error.JPG) hroc - _2016-09-05 08:26:04 +00:00_

**Comment by Hrocc** [comment]
any news on this? do you need more feedback?

**Comment by lippserd** [comment]
Apart from the commit, I strongly suggest to install the PDO adapter from Microsoft: https://github.com/Microsoft/msphpsql/releases. I consider the pdolib extension as not production ready because it seems unmaintained and lacks features like setting attributes. If you use the PDO adapter from Microsoft, make sure to set `pdoType` to `sqlsrv` in your `ressources.ini`.
