### ISSUE TITLE
[dev.icinga.com #12769] Make icingacli ignore proxy settings

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2567]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12769

**Created by twidhalm on 2016-09-22 12:07:33 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-17 10:19:42 +00:00 (in Redmine)_

---

Hi,

I just had an error at a customers site when using `icingacli director config deploy` . When I unset the `HTTP_PROXY` and `HTTPS_PROXY` environment variables, it worked. Since icingacli is used locally it should ignore any proxies. I'm not sure if this is a problem of icingacli or the director module - I'll gladly open an issue in the director queue if this is a better fit.

Cheers,
Thomas

**Comment by Al2Klimov** [comment]
@widhalmt
That's indeed not an IW2 problem because the CLI itself has nothing to do with HTTP requests and IW2 has nothing (yet) the Director could perform HTTP requests with.
But I'm not sure whether you should open a Director issue as `icingacli director config deploy` isn't used locally *by definition*. (May @Thomas-Gelf correct me if necessary.)
