### ISSUE TITLE
[dev.icinga.com #13363] Please put the Status Summary Bar back to the top of the page!

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2630]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13363

**Created by geotek on 2016-11-30 10:06:56 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-30 10:06:56 +00:00 (in Redmine)_

---

In the current Master the small status summary bar has moved to the bottom of the page. This is bad IMO. because it forces me to scroll down to the bottom of every page to see this important summary info. But even at this least prominent page position it is often still not visible because it is overlayed by the Firefox URL status info or by the yellow "Apply" notification bar in Icinga Director.

This feels like putting the table of contents at the end of a book and forcing me to turn every page until I get to it. An overview must be visible at a glance and should not be hidden at the least prominent position of the web page.

I would even take the concept of this status summary bar a step further and put it on top of the Dashboard page too and having the hosts and service infos shown side by side on the same line. For those, who don't like it maybe it would make sense allow disabling it.

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We keep the status bar at the bottom of the page but changed the alignment from left to right. That should help with the URL tooltips generated by browsers. You don't have to scroll down every page because the status bar is sticky and will always be displayed at bottom, regardless of your scrolling position.

Best regards,
Eric
