### ISSUE TITLE
Add contact and contactgroup filters (not for restrictions)

### ISSUE THREAD

**Issue by lum3n** [Icinga/icingaweb2#2708]
It would be great if you could filter for hosts/services which alert to a specific contactgroup. For example something like:

/icingaweb2/monitoring/list/services?service_hard_state=1&service_contactgroup=\*team1\*

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We have to test whether this filter is acceptable regarding performance. I'm not sure whether we'll implement this.

Best regards,
Eric

**Comment by Napsty** [comment]
I'd like to refer https://monitoring-portal.org/t/ldap-users-not-part-of-icinga2-contactgroups/4239/6 to this issue. In my setups I have an array "teams" which dynamically defines the contactgroups using apply rules for a host or service. Because the filter is unable to read a value from an array (see https://github.com/Icinga/icingaweb2/issues/2773) the other solution would be to use contactgroup because this (at the end) is a fixed value in the database:

```
MariaDB [icinga]> select host_id,alias from icinga_hosts where alias = 'inf-monm02-p';
+---------+--------------+
| host_id | alias        |
+---------+--------------+
|       4 | inf-monm02-p |
+---------+--------------+
1 row in set (0.00 sec)

MariaDB [icinga]> select * from icinga_host_contactgroups where host_id = 4;
+----------------------+-------------+---------+------------------------+
| host_contactgroup_id | instance_id | host_id | contactgroup_object_id |
+----------------------+-------------+---------+------------------------+
|                16889 |           4 |       4 |                   1219 |
+----------------------+-------------+---------+------------------------+
1 row in set (0.00 sec)

MariaDB [icinga]> select * from icinga_contactgroups where contactgroup_object_id = 1219;
+-----------------+-------------+-------------+------------------------+-------+------------------------------------------------------------------+
| contactgroup_id | instance_id | config_type | contactgroup_object_id | alias | config_hash                                                      |
+-----------------+-------------+-------------+------------------------+-------+------------------------------------------------------------------+
|              22 |           4 |           1 |                   1219 | WIS   | 3c162d71a20460f32114307aeaa453a41a929c1eba17c162c6c1c55e62d91b2b |
+-----------------+-------------+-------------+------------------------+-------+------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by ggustafsson** [comment]
I don't have any technical feedback on this but I wanted to add that this is a very important feature for us at Volvo Group Connected Solutions. We have almost 70 teams and tens of thousands of checks in total so we need dynamic filtering based on teams. The correct data needed to group objects is already in the system so using static servicegroup lists instead of something dynamic is a real pain in the butt.

So yeah It would be very nice if we could filter on contactgroup arrays eventually like we have done for many years in op5 Monitor. Until then I guess we will just have to automate the creation and syncing of servicegroups through a script.

**Comment by neeej** [comment]
+1 on that this should be a very useful feature.
