### ISSUE TITLE
Acknowledgement mouseover enhancement

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2#2789]
It would be useful to see user and acknowledgement comment on mouseover at acknowledged services/hosts.

**Comment by leeclemens** [comment]
This could be useful on mouseover of the Ack and Downtime icons, currently displays "Acknowledged" and "In Downtime", respectively.

It's not very hard to add this to the second pane screens, but seems like it would require considerable re-work to get it in the main/first listing (since it is passed StdClass with no DB access)

**Comment by lippserd** [comment]
Related to #2887.

**Comment by lippserd** [comment]
Needs feedback whether we'll implement this in the future.

**Comment by lippserd** [comment]
We think about something like this for the new monitoring module.
