### ISSUE TITLE
Event commands not shown

### ISSUE THREAD

**Issue by wrssin** [Icinga/icingaweb2#2815]
In a service view, addicted event_commands are displayed with their params, but I found no way to display if, when, why and what was the status of the executed command. (eg. when a disk runs full, a cleanup job will be triggerd by an event_command. In Icingaweb2 I found no possibility to display some basic Information of the executed cleanup script like when was it triggerd and what was the Plugin Output of this execution).

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I'll see what we can do here.

@dnsmichi Does the IDO have any info about triggered event commands?

Best regards,
Eric

**Comment by dnsmichi** [comment]
Hi,

there's the icinga_eventhandlers table. We do not populate that by default within ido-{mysql,pgsql} since it is unused data (and therefore unneeded queries).

I'm not sure if the columns in there really help though. The command line is not accurate to what Icinga 2 could execute (just a string, no functions). `command_line` and `command_args` are not usable in this case.

https://github.com/Icinga/icinga2/blob/master/lib/db_ido_mysql/schema/mysql.sql#L425

I would stall this and implement such in a new backend which supports what Icinga 2 provides 1:1.

Kind regards,
Michael

**Comment by lippserd** [comment]
Hi Michael,

Supporting this with our new backend only sounds good to me. I close this one for now.

Best regards,
Eric
