### ISSUE TITLE
Icinga Installation on Amazon Linux (AWS)

### ISSUE THREAD

**Issue by ghovat** [Icinga/icingaweb2#2873]
Hi,

it is not possible to install 
- icinga2
- nagios-plugins 

As soon i run the yum installation I get:
`Error: Package: icinga2-bin-2.6.3-1.el7.centos.x86_64 (icinga-repo)
            Requires: systemd
Error: Package: icinga2-bin-2.6.3-1.el7.centos.x86_64 (icinga-repo)
            Requires: libyajl.so.2()(64bit)
Error: Paket: icinga2-libs-2.6.3-1.el7.centos.x86_64 (icinga-repo)
            Requires: libyajl.so.2()(64bit)
`
It this a known issue? I also opened a support ticket from AWS.

Best
Georg

**Comment by lazyfrosch** [comment]
Similar to #2871, a few problems with this issue:

1. You are trying to install icinga2, not icingaweb2 (which this repo is for)
2. Problems with repository or packages go to https://github.com/icinga/icinga-packaging as suggested on https://packages.icinga.com/
3. Amazon Linux is based on RHEL 6, since you are trying to install our RHEL 7 packages on it - that won't work
5. Amazon Linux is not tested by us, nor supported (it would be documented then) - the packaging base is a bit different compared to standard RHEL 6

Please read our answers and respect them.
