### ISSUE TITLE
Can't send external Icinga2 command.

### ISSUE THREAD

**Issue by andymilga** [Icinga/icingaweb2#2879]
got standard installation icinga2, icinga2web at bare metal centos 7 server.
selinux disabled, icinga2 instances started.

Before reboot all was good, after rebbot i got 'Can't send external Icinga2 command.' in icingaweb2 for several actions.

fixed this:
chown -R icinga: /var/run/icinga2/cmd

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I tested a Centos 7 installation and all went fine.
If this issue comes up again, please open a new issue and provide the ownership and permissions of /var/run/icinga2 and /var/run/icinga2/cmd.

Instead of using the command pipe you could also use the Icinga 2 API for sending external commands. This is best practice for Web 2 + Icinga 2.

Cheers,
Eric
