### ISSUE TITLE
Can't send external Icinga command: 404 No objects found. 

### ISSUE THREAD

**Issue by KKeXX** [Icinga/icingaweb2#2884]
I tried to enable/disable Notifications for a Service, but got an this error:
 `Can't send external Icinga command: 404 No objects found. `

For Command Transport I use the API. The permissions for the API User is configured as in the doc's:
`permissions = [ "actions/*", "objects/modify/hosts", "objects/modify/services", "objects/modify/icingaapplication" ]`

As @dnsmichi mentioned in the issue #2854 the correct permissions should be 
`permissions = [ "status/query", "actions/*", "objects/modify/*", "objects/query/*" ]`

After changing this, Everything works as expected. So I think there is an Error in the doc's. Can you please update them?

* Icinga Web 2 version: 2.4.1
* Icinga2 version: v2.6.3

**Comment by vlk-charles** [comment]
Actually, I did not need `status/query` nor `objects/query/*`. Adding `objects/modify/*` is enough but that is because there had been a typo in the documentation, where the correct permissions are:
```
[ "actions/*", "objects/modify/host", "objects/modify/service", "objects/modify/icingaapplication" ]
```
Note the missing final S in `host` and `service`. Maybe the documentation should be changed again to this as it now recommends more permissive configuration than might be necessary.
