### ISSUE TITLE
Show comment icon next to handled/unhandled icon for hosts/services

### ISSUE THREAD

**Issue by bsdlme** [Icinga/icingaweb2#2887]
The old web interface displays a speech bubble when a host or service has an associated comment.
That very useful information is missing in Web2.

## Expected Behavior
![Should be](http://bsd-geek.de/images/icingaweb2.png)

## Current Behavior
![Is](http://bsd-geek.de/images/icingaweb2_now.png)
## Steps to Reproduce (for bugs)

1. Add a comment to a service
2. Browse to /icingaweb2/monitoring/list/services
3. Wonder if there are comments for the displayed services
4. Click every single service
5. Develop an carpal tunnel syndrome when in bigger monitoring environments

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We dropped this feature because it was a performance killer. I don't know yet whether we will reimplement this feature. If we do so, I think it as good idea to show the comment icon only if a comment has been added after the last state change timestamp. What do you guys think?

Best regards,
Eric

**Comment by lippserd** [comment]
We think about something like this for the new monitoring module.
