### ISSUE TITLE
A "<table></table>" is required to print a table in icingaweb2

### ISSUE THREAD

**Issue by passboltUser** [Icinga/icingaweb2#2891]
## Expected Behavior
When using `write-host "<table><tr><th>Name</th><th>Value</th></tr>"` in a PowerShell script to print a table in icingaweb2, it does require a `write-host "<table></table>"` before that, otherwise the table is not created.

## Current Behavior
When I want to print a table using PowerShell and display it in `/icingaweb2`, I need to add an additional `write-host "<table></table>"` otherwise a table starting with say `write-host "<table><tr><th>Name</th><th>Value</th></tr>"` is not working.

Working:
`write-host "<table></table>"`
`write-host "<table><tr><th>Name</th><th>Value</th></tr>"`
`...`
Not working:
`write-host "<table><tr><th>Name</th><th>Value</th></tr>"`
`...`
## Possible Solution
Do not require a `write-host "<table></table>"` before a table start.

## Steps to Reproduce (for bugs)
Try to print a table* using PowerShell and display it in `icingaweb2`.
* say this one:
```
write-host "<table></table>"
 
write-host "<table><tr><th>Name</th><th>Value</th></tr>"
    write-host "<tr>"
    write-host "<td>"name1"</td>"
    write-host "<td>"status1"</td>"
    write-host "</tr>"
}
write-host "</table>"
```

## Context
It took me a bit of time to figure out that a `write-host "<table></table>"` is required.

## Your Environment
<pre>
# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.3-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 17.04 (Zesty Zapus)
  Kernel: Linux
  Kernel version: 4.10.0-26-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 6.3.0
  Build host: a295cf04d827
</pre>

<pre>
# apt policy icinga2
icinga2:
  Installiert:           2.6.3-1.zesty
  Installationskandidat: 2.6.3-1.zesty
  Versionstabelle:
 *** 2.6.3-1.zesty 500
        500 http://packages.icinga.org/ubuntu icinga-zesty/main amd64 Packages
        100 /var/lib/dpkg/status
     2.6.0-2 500
        500 http://de.archive.ubuntu.com/ubuntu zesty/universe amd64 Packages
</pre>

<pre>
# apt policy icingaweb2
icingaweb2:
  Installiert:           2.4.1-1.zesty
  Installationskandidat: 2.4.1-1.zesty
  Versionstabelle:
 *** 2.4.1-1.zesty 500
        500 http://packages.icinga.org/ubuntu icinga-zesty/main amd64 Packages
        500 http://packages.icinga.org/ubuntu icinga-zesty/main i386 Packages
        100 /var/lib/dpkg/status
     2.4.1-1 500
        500 http://de.archive.ubuntu.com/ubuntu zesty/universe amd64 Packages
        500 http://de.archive.ubuntu.com/ubuntu zesty/universe i386 Packages
</pre>

* Operating System and version:
* Enabled features (`icinga2 feature list`):
<pre>
# icinga2 feature list
Disabled features: compatlog debuglog gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command ido-mysql mainlog notification
</pre>
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
<pre>

**Comment by Thomas-Gelf** [comment]
Neither your samples in the issue text nor the (incomplete) pastebin example show valid HTML. You need to close your `table`-Tag. This:

    write-host "<table><tr><th>Name</th><th>Value</th></tr>"

Should read:

    write-host "<table><tr><th>Name</th><th>Value</th></tr></table>"

There is a closing table tag on pastebin, but your code is somehow messed up, you're showing a closing bracket in between. I guess there might be other related code at your side, but my crystal ball is currently under repair. If your real code looks just like the pasted one, this would explain the problem.

Otherwise, showing your full plugin output might help us to reproduce the problem.

> (I posted it to pastebin because I don't know how to disable github's markdown parsing)

Please don't. Paste your code here, select it with your mouse and try to figure out which of the above icons to click. Shouldn't be that hard.

**Comment by passboltUser** [comment]
Ok, selecting the code first and then pressing `Insert code` works for nto parsing.

The table is closed, see  `write-host "</table>"` at last line. Doing `write-host "<table><tr><th>Name</th><th>Value</th></tr></table>"` would create two tables, one with the bold headline and one without headline. The two tables would be distinct from each other.

**Comment by Thomas-Gelf** [comment]
Using `<table><tr><th>Name</th><th>Value</th></tr></table>` in my plugin output works fine, I tested it right now, just to be sure. Please manually run your PowerShell script with the required parameters and have a look at the generated HTML.  Sure, there could be a rendering bug in Icinga Web. Still, your description sounds more like some logical error in the check Plugin. It might return invalid HTML. If in doubt, please show your full plugin output (I know, I repeat myself).

Also please pay attention to [plugin specification](https://www.icinga.com/docs/icinga1/latest/en/pluginapi.html#outputspec), the first output line is treated specially and separated from the rest. It is best practice to have just plaintext on the first line and more details with extended formatting in the following lines. So, your problem might result from your HTML being distributed over the first output line and the so-called "long output". That's why I asked for your full plugin output - and not for some code snippets not reflecting what you are really doing ;)

Cheers,
Thomas

**Comment by passboltUser** [comment]
Thanks, I didn't know about the first and second "long output" thing. I changed `write-host "<table></table>"` to `write-host "some text"` and it works now (the closing table tag at the end correct). The disadvantage is that it needs some text, but this is only a small disadvantage, so it's no problem.
