### ISSUE TITLE
New Hook: Support extensions to add quick actions in monitoring

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icingaweb2#2920]
Here is a new Hook I want to build:

Extra buttons to the `quick-actions` area of a monitoring detail view.

Appending them here:

![bildschirmfoto von 2017-08-11 08-40-16](https://user-images.githubusercontent.com/121874/29203431-0f1eb67a-7e71-11e7-8f3c-8f09056118f3.png)

Integration could be:

* similar to Host/ServiceActionHook
* extending Host/ServiceActionHook to flag a quick action

I'd like your opinion @lippserd @Thomas-Gelf before I start coding.

This is a sponsored feature.

**Comment by lazyfrosch** [comment]
Also @nilmerg

**Comment by lazyfrosch** [comment]
Does this make sense, or better via DetailviewExtension? Trying that out right now...

**Comment by Thomas-Gelf** [comment]
Problem is probably that you can easily run out of space, and then it's going to look ugly. Just imaging all current "Actions" moving up there - because that's what this feature will then attract. Not saying that the current Actions look better ;-)

ipl provides the ActionBar as an object that can be adjusted at any time, even very late in the rendering process. So, we'll have much more possibilities in future. If you want to spend some time on this and neither @lippserd nor @nilmerg have any objections, go for it. Just, we shouldn't promote it loudly. Otherwise everybody moves up there :laughing:

**Comment by lazyfrosch** [comment]
Going for DetailviewExtension for now, until ipl becomes a thing...
