### ISSUE TITLE
Filter to exclude hosts/services that are member of a specific group

### ISSUE THREAD

**Issue by fsirjean** [Icinga/icingaweb2#2934]
Hi,

I couldn't find any doc or issue on this subject, please apology if already answered out somewhere.

Thanks a lot for all the work !

## Expected Behavior
When using filters on hostgroups, hosts being member of more than one hostgroup :
When filtering out a hostgroup (eg : `"hostgroup_name!=foo"`), hosts matching this hostgroup (even if member of other hostgroups) should not be displayed.

## Current Behavior
If host `a` is member of hostgroup `foo` AND hostgroup `bar`, using filter `"hostgroup_name!=foo"`, host `a` is still displayed.
If host `a` is member of hostgroup `foo` and no other hostgroup, filtering works as expected.

## Context
I couldn't find any other way to display strictly "all hosts but hosts which are member of group foo".
Encountered both in views (eg: `/icingaweb2/monitoring/list/services?service_problem=1&hostgroup!=foo`) and roles permissions (see documentation: [06-security](https://github.com/Icinga/icingaweb2/blob/master/doc/06-Security.md#example-2-hostgroups)).

## Your Environment
* Icinga Web 2 version: 2.4.1
* Modules used: doc (2.4.1), monitoring (2.4.1), pnp (1.0.1)
* Icinga2 version used: r2.6.0-1
* Operating System and version: debian stretch (9.0), linux 4.9.0-2-amd64
* Enabled features: checker command ido-mysql mainlog notification perfdata

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Unfortunately excluding hosts with such a filter is not possible yet and somehow related to #1649. I can't tell you when this issue is going to be scheduled.

Best regards,
Eric

**Comment by nilmerg** [comment]
It's now scheduled for the next major release v2.6.0.

The issues we're looking at here are the following:

1) Any amount of unequal comparisons to linked objects (e.g. `list/hosts?hostgroup_name!=foo` as well as `list/hosts?hostgroup_name!=foo&service_description!=bar`) return unwanted/wrong results.
2) Multiple equal comparisons to linked objects (e.g. `list/hosts?hostgroup_name=foo&hostgroup_name=bar`) return no results at all. (See #1649)

Once this issue is resolved the following will change:

1) Such a comparison returns less results. (i.e. No hosts which are a member of any hostgroup besides `foo` (while being a member of `foo`) and no hosts which have any other service other than `bar` (while having one named `bar`))
2) This does return results. (i.e. All hosts which are a member of the hostgroups `foo` and `bar`)

Note that 1) is a breaking change. While the results are clearly wrong there are still results returned on which some may rely upon. This needs to be clearly mentioned in the release notes.
