### ISSUE TITLE
Travis CI: PHP 5.3 builds fail on trusty

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icingaweb2#2948]
PHP 5.3 support only is available in precise which was discontinued on Travis CI. The current build containers now use trusty by default (Q3 2017).

https://blog.travis-ci.com/2017-04-17-precise-EOL
travis-ci/travis-ci#2963

Either we remove the tests, or find a possible workaround for PHP 5.3. @lazyfrosch @lippserd ideas on that?

**Comment by lazyfrosch** [comment]
I'll have a look

**Comment by lazyfrosch** [comment]
* [Cannot install PHP 5.3 in Trusty #7693](https://github.com/travis-ci/travis-ci/issues/7693)
* [Drop PHP 5.3.29 and below for Trusty #2963](https://github.com/travis-ci/travis-ci/issues/2963)

Since Travis should keep support for Precise for at least a while, we should be able to tune the build matrix to build 5.3 on precise and the rest on trusty.
