### ISSUE TITLE
Use PHP's "new" password hashing API and "stronger" algorithm

### ISSUE THREAD

**Issue by lippserd** [Icinga/icingaweb2#2954]
As discussed in #2436 and #2738 we have to replace MD5-Crypt w/ something "stronger". We should do this once we raise our PHP dependency to 5.6. This allows us to use the new functions related to password hashing which have been introduced w/ PHP 5.5. The default there is bcrypt which I would stick to then.

**Comment by Al2Klimov** [comment]
FYI:
"Um (...) Angriffe zu verhindern, sollten Webseiten-Betreiber die Passwörter ihrer Nutzer mit Verfahren wie bcrypt (...) speichern. Diese sind darauf ausgelegt, dass ein Angriff möglichst viel Ressourcen benötigt (...)." – c't 20/17 S. 43 Abs. 2

Translation from German via Google Translate (verified by me):
"To prevent (...) attacks, web site operators should store the passwords of their users using methods like bcrypt (...). These are designed so that an attack requires as much resources as possible (...)."
