### ISSUE TITLE
Make overdue (or unreachable) checks better visible

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2#3212]
Hi,

Could overdue or unreachable checks be shown with a lighter color or more 'greyish'? From other issues I understand that visualizing unreachable (where dependencies hit) is hard with the current IDO schema. (There are other issues for that already open, like #2232 )

But could at least every check, that was not checked in time be shown, no matter if overdue or unreachable be shown as outdated? I know there is the "last check result" and the dot besides check source but I think it would be very helpful to have this clearly visible from every overview, dashoard etc.. In other words I want to see it at one glance without having to open the detail view or the overdue dashboard.

What could be a bit tricky is the fact that not every check is executed at the exact time when it is scheduled. So maybe making it grey-ish after two times the regular check interval could be a good policy.

Cheers,
Thomas

**Comment by sahnd** [comment]
+1

**Comment by lippserd** [comment]
Hi Thomas,

Thanks for the report. We'll think about how this could be implemented best.

Cheers,
Eric

**Comment by TheBigfoot** [comment]
I also have a question regards this visibility:
When a service fails after hostalive went down on the same host, the service is at least marked as handled. Why is this not possible for defined dependencies? Wouldn't it be the same handling?

**Comment by marcofl** [comment]
I described about the same requirement in https://github.com/Icinga/icinga2/issues/6092 which is now closed, because it's not really related to icinga2 itself. 

@TheBigfoot What you're referring to is the implicit service to host dependency, which marks services "handled" when the host is not-ok. I agree that this should also be done the same way for custom defined dependencies. https://www.icinga.com/docs/icinga2/latest/doc/03-monitoring-basics/#implicit-dependencies-for-services-on-host

We really need this, because we mainly work without notifications in icinga2 but have a dedicated Ops guy watching icingaweb2, then services which are "handled" by a dependency should not pop up. Also we don't want to disable active checks, because a check can still produce valid performance data even if parent service is not-ok (or the service itself is not okay) and then we would loose valuable performance data for debugging.

**Comment by marcofl** [comment]
this seems to be related or a duplicate https://github.com/Icinga/icingaweb2/issues/2510

**Comment by lippserd** [comment]
Hi,

I played around with greyish colors and an additional icon for overdue checks because of accessibility. But I'm not really happy with that since it introduces more information and new states in our frontend which the user has to learn and interpret.

Alternatively, we could introduce this as an additional number in the tactical overview and have this number also available in the dashboard.

I'm not sure yet what's the best tradeoff between highlighting this information somewhere without overloading the interface with more and more icons and colors. So, I'll postpone this for a version after the 2.6.0 release.

Best,
Eric

**Comment by TheBigfoot** [comment]
@lippserd why is it planned to have additional states for this? Right now the implicit host <> service dependencies also don't show of with other states.

**Comment by miso231** [comment]
Is there any chance you add this to 2.7.0 version?

**Comment by MarcusCaepio** [comment]
Yep, any news about this, would be very nice @lippserd

**Comment by widhalmt** [comment]
I think, we don't need additional states, too. Just another color / pattern and maybe a short hint / icon. I'm totally cool with this being only visible in Web.

**Comment by MarcusCaepio** [comment]
imho it should be handled as same as the host down -> services off dependency

**Comment by widhalmt** [comment]
ref/NC/603111
