### ISSUE TITLE
Dashlet external URL

### ISSUE THREAD

**Issue by jelayeb** [Icinga/icingaweb2#3234]
i know that external urls can not be displayed in Icingaweb2 dashboard, but it would nice to allow this, as sometimes we have different monitoring systems and we want to have an overview in one place. 
i know it will be difficult to fit other pages inside the dashlets but it would be nice to have and every rose has its thorn.

**Comment by lippserd** [comment]
Web 2 ships with an action which allows to render any page that does not violate the page's [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors) using `<iframe>`. You may try to add the following URL to your dashboard:

`iframe?url=https://www.icinga.com/`

Please note that we may change this action in the future because at the moment it is possible to render any page. In the future, admins configure which pages are allowed for this action and less privileged users have to choose from this set, e.g. `iframe?name=icinga`. I'll push a PR in a second which improves rendering `iframes` in the dashboard.

Please test the PR and give us feedback.

**Comment by Al2Klimov** [comment]
As discussed w/ @lippserd (offline):

We could let `iframe?url=https://www.icinga.com/` working by implementing an URL (pattern) whitelist instead of `iframe?name=icinga`.

**Comment by lippserd** [comment]
@Al2Klimov Could you please open an enhancement request for your suggestion? I like the idea.

**Comment by Al2Klimov** [comment]
#3296
