### ISSUE TITLE
Missing Custom Variables

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2#3336]
Host- and Service-CustomVars are not displayed any more.

* No errors in logfiles
* IDO entries seem to be okay

I think it's related to https://github.com/Icinga/icingaweb2/pull/3220.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.5.1
* Version used (`icinga2 --version`): 2.8.1
* Operating System and version: CentOS 7.4

**Comment by lippserd** [comment]
This issue was related to an Icinga 2 issue. Somehow Icinga 2 correctly updated the config_hash in the icinga_hosts and icinga_services tables but was unable to fill the icinga_customvariablestatus table correctly. If you don't change the host or service after that, the config_hash will not change and thus icinga_customvariablestatus will never be written. You can easily fix this by truncating the icinga_hosts and icinga_services table and restarting Icinga 2 after that.

**Comment by lippserd** [comment]
Same as #3193
