### ISSUE TITLE
Auto-refresh behavior of search and filter 

### ISSUE THREAD

**Issue by claudekenni** [Icinga/icingaweb2#3348]
## Expected Behavior
The search function should only start the actual search when someone presses enter 
You should be able to adjust your filter and only have it run when clicking the apply button.

Basically we need a way to deactivate the auto-refresh for these.

## Current Behavior
The search function currently starts searching as soon as the string is being entered into the Field or something in there is changed. Sometimes I have to change a few characters within the search and as soon as I Enter one its starts the search. In the middle of it, it will finish one part of the search and the cursor will jump to the end while I'm still Entering stuff.

The Filter function starts as soon as you go in there and when adding a new filter into it it directly starts to update. This can take a long time with several thousands of nodes and services.

**Comment by nilmerg** [comment]
Hi, thanks for reporting!

We're basically talking about two different issues here:

1. The menu's auto refresh resets the cursor position to the end
2. The search reacts too fast to user input

To solve the auto refresh issue I can think of the following solutions:
* Remember and restore the cursor position instead of moving it to the end
* Suspend the auto refresh as long as the user is interacting with the input

The first one might be a bit tricky and I don't know if it works cross browsers. (It **is** possible, though)
The second one is probably the simplest and easiest one, but we may run into issues with the auto refresh being stuck.

To slow down the search's reaction I can think of the following solutions:
* Do not search automatically. Wait for the user to press ENTER.
* Do not search instantly. Delay the search every time the user interacts with the input.

Both are easy to implement. But the second has probably the least UX impact. (Regarding the current functionality, it's not that pressing ENTER is bad UX...) Hence it'd be my preferred one.

I'd vote in both circumstances for the delay/suspension. But others are welcome to comment. (@lippserd ;) )
