### ISSUE TITLE
Assets loaded with 1.6-3s delay on FireFox

### ISSUE THREAD

**Issue by karlisup** [Icinga/icingaweb2#3394]
Hi,
When first time opening login or any other page of FireFox or reloading the page by clearing the cache assets are being loaded by a huge delay 1.6-3s leaving interface un-styled (screenshots provided below). To fix this issue we have inlined some style and svg and also provided an loading screen which is an ugly quickfix. There is a noticeable performance issue also on Chrome, but it doesn't affect user experience that much.

## Current Behavior
![Image of Yaktocat](https://image.ibb.co/kv5Ypc/firefox_login.png)
![Image of Yaktocat](https://image.ibb.co/kj8gaH/firefox_dashboard.png)
![Image of Yaktocat](https://image.ibb.co/b18WaH/firefox_csswaiting.png)

## How to reproduce
1. Open webpage [Icingaweb2 login page](https://www.icinga.com/demo/authentication/login)
2. Reload page by clearing cache
- Press "Ctrl + F5" or press "Ctrl + Shift + R" (Windows,Linux)
- Press "Command + Shift + R" (Mac)
3. _Voila_ 

## Environment
Mac:
Firefox Developer edition 60.0b4 (64-bit)
Firefox Quantum 59.0 (64-bit)
Windows:
.. unknown versions but also there it was not working.

**Comment by lippserd** [comment]
Hi,

I don't know why you've provided screenshots of our demo system. Sure, you may have hit a time where the server had to serve many requests. Is your own Icinga Web 2 installation slow? What's the load of your servers? Does your ad blocker interfere here maybe?
The only chance to reduce the time to build our assets is to offload this process to a separate daemon. But this is not going to be implemented in the near future. We could introduce a loading screen or something. But since we load JavaScript and CSS only once this is not really a high priority feature for us. There should be no need to clear the cache. What exactly do you expect from us now?

Cheers,
Eric
