### ISSUE TITLE
bad performance maybe related to custom variables

### ISSUE THREAD

**Issue by marcelfischer** [Icinga/icingaweb2#3460]
Since we make use of custom variables and also use them for "monitoring/filter/objects" we have a higher load on our mariadb server and performance is not as good as before.

We have 376911 rows in icinga_customvariables and icinga_customvariablestatus

## Expected Behavior
Performance should be better of course ;-)

## Current Behavior
We using the search or filter the performance is quite bad. Some parts of the icingaweb2 are loading longer as before.

## Possible Solution
Currently no Idea since its only a assumption

## Your Environment

* Icinga Web 2 version and modules (System - About):     2.5.1
* Version used (`icinga2 --version`): 2.7.2-1
* Operating System and version: RHEL 7.4

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Filters on custom variables have quite a big performance impact because we don't/can't have indices for them in the database. We're working on a new data backend which is expected to be released in Q1 2019 which also addresses this issue. Sorry but I have to close this one because there's not much you can do right now.

Best,
Eric
