### ISSUE TITLE
Winter theme causes high CPU usage

### ISSUE THREAD

**Issue by mateusz-gozdek-sociomantic** [Icinga/icingaweb2#3569]
## Expected Behavior

Nice animation with low CPU usage, while enjoying falling snow (Winter theme).

## Current Behavior

CPU usage sitting at around 50% according to chromium (Chromium 68.0.3440.106 Arch Linux) task manager, calmly warming our office.

## Possible Solution

According to https://stackoverflow.com/a/35908679, `background-*` animating should be avoided.

Alternatively Winter theme can be just removed.

## Steps to Reproduce (for bugs)

1. Go to user preferences
2. Enable Winter theme

## Context

While this is not a big issue, as it's only theme, but still if some people change it, and this may result in overheating of laptops and extensive battery usage, which is definitely not good.

## Your Environment

Chromium version: `Chromium 68.0.3440.106 Arch Linux`
Performance profile from Chromium: [Profile.json.zip](https://github.com/Icinga/icingaweb2/files/2345940/Profile.json.zip)

**Comment by Thomas-Gelf** [comment]
I'd say **it works as designed**:tm:: heating your office is a desired side-effect during cold Winters :rofl: :rofl: :rofl:

Jokes apart, unless this is going to be fixed in some way there is a workaround for you: an Administrator can enforce themes on a global level by enabling `Configuration` -> `Application` -> `General` -> `Users Can't Change Theme`

If you want your users to still be able to change themes while disallowing only this specific one, the only way is to remove (`/usr/share/icingaweb2/`)`public/css/themes/Winter.less` - or to replace it with an empty file. Such hack however needs to be repeated after each upgrade of Icinga Web 2.

Cheers,
Thomas

**Comment by mateusz-gozdek-sociomantic** [comment]
Thanks for the workaround, I currently just commented out animation style, so snow is just frozen.

It's absolutely low prio issue, but maybe someone with little CSS experience can catch easy contribution with it.

**Comment by nemanja-boric-sociomantic** [comment]
OTOH I keep my headphones on laptop and I open Icinga to get a warm feeling when putting them on after five minutes. Please make this configurable.

Relevant XKCD: https://imgs.xkcd.com/comics/workflow_2x.png

**Comment by nilmerg** [comment]
Well, I guess this is really a non-issue unless someone's office burns down. (For which we're certainly *not* liable)

Unless someone really comes up with a real solution it's sufficient that it's an optional theme. So this may rather get a *Only enable at your own risk* warning. Or we simply remove this theme from upstream. (Appropriately labelled as *hotfix*)

Hence, closed. For now. Just submit a PR for whichever solution you'd like.
