### ISSUE TITLE
Better distinction between hosts and services (more clickable looking)

### ISSUE THREAD

**Issue by davekempe** [Icinga/icingaweb2#3615]
When I watch certain users use the web interface, I can see they struggle to distinguish between hosts and services most often. 
This is apparent for example in the Service Problems column as per this picture:

![Service Problems](https://i.imgur.com/DCYBJWN.png)

The tendency is for them to click on the hostname and then get lost in the interface a little as it didn't show the service they were expecting.

Even in recently recovered services, they often click on the hostname, and either don't see the services tab, nor the little icon they can click to show the services. Perhaps the interface elements don't appear as 'clickable' as they could, or perhaps they need a larger hint as to where services are. I often have to guide new users as to where to click to see the services correctly.

I'm not sure what the solution is, but I'm hoping someone can suggest a neat way to make the distinction  little broader, so users can find services more easily.
In fact, the word '12 Services' in this image doesn't even look clickable.

![Where is services again](https://i.imgur.com/vfSLfw2.png)
by contrast the 'Check Now' is clearly clickable, due to it being a different font and colour.

Perhaps just making "12 Services" more similar to "Check Now", with a larger font and an icon would make it clearer for people?

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We'll see what we can do here.

Cheers,
Eric

**Comment by b33rcity** [comment]
Simply underlining the service name in the list items would make them look like a link and encourage users to click the service rather than the host. Same with the "Services" link on the host view.

**Comment by nilmerg** [comment]
@flourish86 Please take a look at this one and propose a solution.

**Comment by flourish86** [comment]
> When I watch certain users use the web interface, I can see they struggle to distinguish between hosts and services most often.

Firstly, thanks for the valuable feedback. It's always helpful to hear, what certain problems users have.

> The tendency is for them to click on the hostname and then get lost in the interface a little as it didn't show the service they were expecting. …

The primary problem might not be the appearance of the clickable elements. I assume, that the first item to click on in the header is the host is the most confusing part of this.

We will approach the redesign we already elaborated in course of a bigger UI redesign sprint. We put the service name first, because it's the primary item and highlight clickable elements with a bold font (we shouldn't underline because readability suffers, especially on a high info dense UI like Icinga Web).

It will look like this and imho is totally worth the term *neat* 😉 

![Screenshot 2019-05-27 at 11 22 27](https://user-images.githubusercontent.com/6977434/58410078-beaa4380-8071-11e9-8c25-7577a9818a56.png)

> Perhaps just making "12 Services" more similar to "Check Now", with a larger font and an icon would make it clearer for people?

We distinguish visually between clickable links that lead to a view (aka Icinga Web actions) and actions that affect the objects themselves (aka Icinga Core actions). Blurring that distinction will confuse users, so we won't use the same design.

It'd make sense to find a more consistent appearance for clickable elements throughout the UI, though.
