### ISSUE TITLE
It is required that a default timezone has been set using date.timezone

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingaweb2#3626]
## Expected Behavior

I don't have to set date.timezone as [Icinga Web 2 falls back anyway](https://github.com/Icinga/icingaweb2/blob/9f15bda698952a369a2bcf949842548a60e447ac/library/Icinga/Application/ApplicationBootstrap.php#L624) in the rare case that my browser doesn't provide any TZ offset.

## Current Behavior

I have to configure it every damn time.

## Possible Solution

Replace the error in the setup wizard with a warning.

## Steps to Reproduce (for bugs)

Run the setup wizard as usual.

## Context

Testing something with a fresh IW2.

## Your Environment

The latest bleeding edge hipster stuff from you.

**Comment by dnsmichi** [comment]
This has been a common error users make for 9+ years, when not required explicitly. I don‘t think this should be made optional again.

**Comment by Al2Klimov** [comment]
Error? Which error? If there have been an error, then because the first paragraph of this issue didn't apply that time.

**Comment by Thomas-Gelf** [comment]
Please be extra careful when touching this. Motivation for this requirements was that Linux distros [crippled](https://derickrethans.nl/distributions-please-dont-cripple-php-or-red-hat-stop-fucking-around.html) PHP timezone detection in various ways. I can remember that at the time being our main problem was RHEL 6 reporting some weird default value, so there was no good way to detect whether a timezone had been configured. Eventually this is no longer a problem since we dropped support for 5.3 - some research / intensive testing would definitively help.

I'd also love to get rid of this, but once again: please be cautious and very, very careful: this could cause weird problems. That's why we opted for this hard requirement - it allows us to make the assumption that everybody configured a default value.

**Comment by Al2Klimov** [comment]
If "there [is] no good way to detect whether a timezone had been configured", how can you safely tell that our hard requirement is fulfilled by the user?

**Comment by Thomas-Gelf** [comment]
Guess no one really remembers all the details, you might want to ask @lippserd, eventually he can. But please believe me - there have been weird annoying issues, and different Linux distributions showed different behavior. Please talk to @lippserd if you have the desire to tackle this, I'd discourage doing so without intensively testing all supported distributions.

**Comment by Thomas-Gelf** [comment]
As you mentioned this paragraph:

> ...the rare case that my browser doesn't provide any TZ offset.

Please note that this code also runs on CLI, as a check plugin and in background jobs and daemons. Missing timezone settings might affect components like specific log writer implementations. Every emitted E_NOTICE is deadly.
