### ISSUE TITLE
LDAP escape character for comma

### ISSUE THREAD

**Issue by ProjectPatatoe** [Icinga/icingaweb2#3648]
When editing / entering a LDAP resource, I run into issues with escape characters for "Bind DN". Normally it would be `CN=Smith\, John,OU=blah ... and so on`. It validates as OK. 
However when I save it, it gets saved as  `CN=Smith\\, John,OU=blah ... and so on` and this is now "Invalid Credentials" because of the extra `\`

My current work around is to edit /etc/icingaweb2/resources.ini and fix it there.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.6.2
* Version used (`icinga2 --version`): r2.10.2-1
* Operating System and version: 18.04.1 LTS

**Comment by nilmerg** [comment]
Hi,

just don't escape anything? Doesn't it work without it?

I suppose the reason you think you'll need to escape commas here is due to something else that's also processing the bind dn. Though, Icinga Web 2 does not and passes it right through to LDAP which shouldn't care about commas here as it's the standard separator in distinguished names.

**Comment by ProjectPatatoe** [comment]
without escaping it. (`CN=Smith, John,OU=blah...`) it fails to validate with "Invalid Credentials"

**Comment by nilmerg** [comment]
Oh, I see. It's in your username where it certainly needs to be escaped. My bad.

**Comment by trendchiller** [comment]
same error here

**Comment by gasperno** [comment]
I get similar error with bind_dn => 'domain\username',
The output would be bind_dn = 'domain\\username' and it leads to invalid credentials issue as OP mentioned.
