### ISSUE TITLE
Function of icingaweb2-module-x509

### ISSUE THREAD

**Issue by leeclemens** [Icinga/icingaweb2#3658]
I am creating this to create a discussion as to the usage/purpose of the relatively new icingaweb2-module-x509 module.

## Expected Behavior
IcingaWeb displays the current status of various hosts/services/plugins.

## Current Behavior
It appears the icingaweb2-module-x509 adds status checking behavior, according to its description. If I'm wrong on this, please let me know and disregard.

## Possible Solution
The new "display" layer module should display, and not actually perform the checking of the status. If this data is stored with existing (or new) checks for another method, it seems reasonable as a web layer for displaying those results.

## Steps to Reproduce (for bugs)
N/A

## Context
Context is that the web should be the display layer, as opposed to performing verification/checking of the status, as it appears to be.

## Your Environment
N/A

**Comment by nilmerg** [comment]
Hi,

the x509 module is intended as certificate harvester, so to say. Sure, it shows details about a certificate's validity (and its chain) but the main reason for doing so is only of informational nature. In order to perform a *status check* (as you would see it) would require a specific [check command](https://github.com/Icinga/icingaweb2-module-x509/issues/16) in Icinga 2 and proper integration in the environment there.
