### ISSUE TITLE
Monitoring not a build in module 

### ISSUE THREAD

**Issue by HLA-systeem** [Icinga/icingaweb2#3719]
Running Ubuntu. 
After installation the monitoring module was nowhere to be found in:

`/usr/share/icingaweb2/modules`

Only `setup`, `test`, `migrate` and `translation` were present.

 The doc refers to monitoring as a build in module that should be present.

**Comment by nilmerg** [comment]
Hi,

this is usually ensured by the package. Which package did you install? (name and source) Which Ubuntu version exactly?

**Comment by HLA-systeem** [comment]
Thank you for your time,

I added the repository from 'deb http://packages.icinga.com/ubuntu icinga-xenial main'
From here I installed `icingaweb2` , `libapache2-mod-php` and `icingacli`

Ubuntu 16.04.5 LTS
Release 16.04

**Comment by HLA-systeem** [comment]
I purged and reinstalled everything from there and now I don't get any module anymore. 

I removed all name matching files with icingaweb2 beforehand. Aside from dpkg, apache related ones and /usr/share/lintian/overrides/icingaweb2. As to ensure it was a complete reinstallation.

**Comment by nilmerg** [comment]
You may have omitted recommended package installation. By installing these the `monitoring` module should properly install.

Besides, manually removing files which where initially created by your package manager is probably not the best idea. If you've installed them with the manager, also remove them with it.

For further questions about this matter please head over to our forums https://community.icinga.com.

**Comment by HLA-systeem** [comment]
Just to make sure you know. These packages were the ones suggested by https://icinga.com/docs/icingaweb2/latest/doc/02-Installation/ , I would like to inform you this doc needs to be updated then. 

I will move to the forums then, thank you for the advice.

**Comment by HLA-systeem** [comment]
It's also the same as in the other documentation on here https://github.com/Icinga/icingaweb2/blob/master/doc/02-Installation.md 
So either I have not omitted the recommended package installation, or all your documentations are currently outdated.

**Comment by nilmerg** [comment]
With *recommended packages* are optional packages meant which are linked to the one that is installed. These are not needed to be installed explicitly, they're installed automatically by your package manager.

For the package `icingaweb2` these are the following on Ubuntu:

`apache2 | httpd, libapache2-mod-php | php, php-cli, php-curl, php-ldap, php-json, php-intl, php-imagick, icingacli, icingaweb2-module-monitoring, icingaweb2-module-doc`

Your package manger though may be configured so that these are not installed automatically. Or you've passed a switch (such as `--no-recommends`) to it while installing Icinga Web 2.
