### ISSUE TITLE
[Feature-Request] Display comments to associated service

### ISSUE THREAD

**Issue by pdorschner** [Icinga/icingaweb2#3728]
It should be possible to display the according comments to the services via the addColumns feature right beside the actual service states to achieve a higher and better overview if an service incident is actually handled or at least properly acknowledged or worked on.

For a better understanding:
<img width="1044" alt="Screen Shot 2019-03-26 at 2 04 36 PM" src="https://user-images.githubusercontent.com/37802318/55000805-98194f00-4fd3-11e9-9e2e-41d342bf4415.png">

## Expected Behavior

Comments should be associated to the correct service in one row.

## Current Behavior

Comments and services are mixed up.

## Your Environment

* Icinga Web 2 version: 2.6.2
* Icinga 2 Version used: 2.10.4

**Comment by nilmerg** [comment]
Hi Philipp,

firstly, whether an incident is handled or not should already be visible because we're displaying a lighter color. That's the case if it's acknowledged or in a downtime. How *properly acknowledged* is defined is probably out of scope here.

Showing the comments of a host/service as part of the list is very difficult. Your example already shows two comments. How many of the hosts/services do you think are still visible if there are way more comments? You'd see plenty of empty space, that's for sure. And displaying all of them in a single row has nothing to do with *higher and better overview*, imho.

If this is just about *proper acknowledgements*, please elaborate what makes an acknowledgement improper. We may rather do something to prevent them in the first place.

**Comment by lippserd** [comment]
I agree to @nilmerg thoughts. That's exactly what acks are for.
