### ISSUE TITLE
monitoring hostgroup-filter filters out hostgroups that are fully contained in hostgroups accepted by the filter

### ISSUE THREAD

**Issue by angelorosacewp** [Icinga/icingaweb2#3739]
## Expected Behavior

I create two hosts (1, 2) and two host groups (A, B). Group A contains 1 while Group B contains 1 and 2. I set up a user which has a monitoring filter on hostgroups set up as "hostgroup_name=GroupB". If I log in with that user I just created and I go on overview to check on the hostgroups I just see GroupB which contains both host 1 and 2. At this point I would have expected to see also group A since it is fully contaied inside group B. 

## Current Behavior

Right now just group B is shown.

## Steps to Reproduce (for bugs)

1. create two hosts
2. create two host groups
3. assign one host to one group and both hosts to the other group
4. create a user with a monitoring filter for hostgroups in which you just accept the group that contains both hosts
5. log in with the new user
6. go in monitoring>host groups
7. you see just one group but you should be able to see both since one is fully contained in the other

## Your Environment

* Icinga Web 2 version and modules (System - About):
Director Version: 1.6.2
Operating System and version: Centos 7
PHP versions: rh-php71-php-fpm-7.1.8

![crop](https://user-images.githubusercontent.com/47357312/55805419-b0fb2780-5ade-11e9-8773-2509d7eb8e67.png)

**Comment by nilmerg** [comment]
Hi,

this works exactly as it should. You're filter is targeting a hostgroup's name after all. And `GroupA` is not labelled `GroupB`. #3349 is related, yes, but that's a new feature and not a bug.

What you're describing/expecting is what the result would be if your filter is targeting a host's name. `host_name=1` would show you both groups because both have a host labelled like this.

If you have further questions about this topic, please head over to our forums: http://community.icinga.com
