### ISSUE TITLE
Support custom action labels

### ISSUE THREAD

**Issue by dasJ** [Icinga/icingaweb2#3754]
## Is your feature request related to a problem? Please describe.

When having multiple actions defined in icinga, icingaweb2 just lists them as "Action 1", "Action 2", …

## Describe the solution you'd like

A way to change the label, maybe change the type in icinga to a dict.

## Describe alternatives you've considered

Memorize what Action 1 and 2 are and hope they are the same for every host and service.

## Additional context

Screenshot:

![image](https://user-images.githubusercontent.com/4971975/56358157-1eddd800-61de-11e9-87b8-4b9ea5984053.png)

**Comment by nilmerg** [comment]
Hi,

if you want customizable labels for action urls I'd suggest you create custom host- and service-actions in your profile's navigation settings. Then share those to other users so that they can see them as well.

The `action_url` attribute won't receive much attention anymore. It's for UI related stuff which should be kept there and not mixed with Icinga's configuration.
