### ISSUE TITLE
Flickering at mouse over in Firefox

### ISSUE THREAD

**Issue by phil-or** [Icinga/icingaweb2#3791]
## Describe the bug
Since the update from 2.6.2 to 2.6.3 there is a bug in the menu bar. 
If there are problems or a change in the Icinga-Director, a small icon with the number of problems is displayed in the menu bar on the left side. 
Since 2.6.3 are that menu bars higher then others and if you move your mouse over the bar, it flickers. 

Our test results showed that the bug occurs only with Firefox, not with Edge or IE

## Screenshots
![image](https://user-images.githubusercontent.com/36534023/58172164-16266900-7c98-11e9-85ff-0b6f1f2cbec4.png)
![image](https://user-images.githubusercontent.com/36534023/58172513-1ecb6f00-7c99-11e9-9338-b57228f7bfbd.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.6.3
* Web browser used: Firefox 60.7.0esr (64-Bit)
* Icinga 2 version used (`icinga2 --version`): 2.10.4
* PHP version used (`php --version`): 7.1.8
* Server operating system and version: CentOS7

**Comment by nilmerg** [comment]
@theFeu @flourish86 Please investigate this. Might be linked with #3187.

**Comment by flourish86** [comment]
The problem here is that the 'white-space: nowrap` attribute conflicts with the `float: right`. This is a known bug for the current ESR version. 

See [here](https://stackoverflow.com/questions/26306864/firefox-float-bug-how-do-i-get-my-floatright-on-the-same-line) (Stack Overflow).

Options, we have imho:

1) Leave out the `white-space: nowrap`, which is necessary for the `text-overflow: ellipsis` to work
2) Position the badge with position absolute, which may cause further side effects and problems
3) Leave it as it is and wait until Firefox make their homework

I don't see the effort and risk of shortcomings of 1) and 2) as appropriate, so I would stick to Option 3.

**Comment by nilmerg** [comment]
Closing this now without fix. Mozilla is tracking this bug [here](https://bugzilla.mozilla.org/show_bug.cgi?id=488725) and released a fix with v63. The next ESR release based on v68 is due in just four weeks.
