### ISSUE TITLE
Indicate empty values in detail view

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingaweb2#3907]
## Description
Empty values should be indicated as "empty". Just leaving it out, looks like something went wrong.

## To Reproduce
E.g.: Navigate to Detail view of an object with empty plugin output. The heading 'Plugin output' is displayed at the top of the content area, followed immediately by the next heading.

## Expected behavior
The user should be noticed that there's no plugin output.

## Screenshots

Screenshots taken in high-contrast theme.

![Artboard Copy](https://user-images.githubusercontent.com/6977434/62690931-ee5cbc80-b9cd-11e9-9819-b268cab257a5.jpg)

![Artboard Copy](https://user-images.githubusercontent.com/6977434/62690937-f157ad00-b9cd-11e9-9001-c5310aab06ee.jpg)

## Your Environment
Icinga Web 2.7.0

**Comment by nilmerg** [comment]
That this is not an error is really an edge-case. Usually a check returns output. If no output is shown it's 99% of the time an issue with how the check has been executed. (Either by Icinga or a wrapper script)

Hence, I'm not bothered at all that it implies something is wrong the way it looks currently. Something **is** wrong after all. (In your example anyway, since the checks are pending.)

**Comment by flourish86** [comment]
> Hence, I'm not bothered at all that it implies something is wrong the way it looks currently. Something is wrong after all. (In your example anyway, since the checks are pending.)

Yes, but having an error should not be communicated through UI being buggy. Even if it's an edge-case, we should have this solved. UI should be clear and transparent especially in edge-cases.

**Comment by nilmerg** [comment]
The references PR is closed, so I'll close here as well. Icinga DB Web handles this fine.
