### ISSUE TITLE
Show "Last Login" per user

### ISSUE THREAD

**Issue by winem** [Icinga/icingaweb2#3914]
## Is your feature request related to a problem? Please describe.
I have no overview who actually uses their icinga2 account and who doesn't. 

## Describe the solution you'd like
It would be nice to see not only the creation and modification date for a user but also the last login.

## Additional context
This information is not stored in the database yet.

**Comment by nilmerg** [comment]
Hi,

thanks for the suggestion. Did you know about the [audit module](https://github.com/Icinga/icingaweb2-module-audit)? It's not an overview, though it tracks logins. And also not just those of database users.

And to be honest, while it's good idea, it's not a priority to us. Not only due to the audit module, but also because it only applies to database users. And think for a moment about the habit of your users. Do they tend to keep their browsers open all the time? If so, they won't login that often so that you get a clear picture of their activity. :wink:

**Comment by winem** [comment]
Hi, 

ok, I completely forgot about the audit module. This has some additional benefits and provides much more insights. I will go with that one. 

And yes, you're totally right regarding the open browser tabs. This was more meant to be an indicator if it was used in the past weeks or maybe at all or not. Thanks for the link to the audit module!

**Comment by nilmerg** [comment]
Okay, fine. Then I'll just close this since the audit module is all you need. :sweat_smile:
