### ISSUE TITLE
Menu item state badges only appear after an auto refresh

### ISSUE THREAD

**Issue by theFeu** [Icinga/icingaweb2#3923]
## Describe the bug
I would expect the badges to show up on the initial load already.
It feels kind of weird that something only pops up after an auto refresh.

## To Reproduce
1. Make sure you have auto refresh enabled
2. Load any page
3. Wait
4. Badges appear after the auto refresh

## Expected behavior
I expect that, after menu loaded the badges show immediately. 

## Screenshots
Initial load:
![image](https://user-images.githubusercontent.com/22217062/63101267-0194fc80-bf79-11e9-8751-a21fd78b168e.png)

After auto refresh:
![image](https://user-images.githubusercontent.com/22217062/63101279-078add80-bf79-11e9-8364-743e762ffb73.png)

## Your Environment

Icinga Web 2 2.7.1 in Vagrant Box

## Additional context
After initial menu load without the calculated badges (for speedy menu loading) we need to trigger the reload again for the badges to be shown..?

**Comment by theFeu** [comment]
Tested again on the 2.7.3 and they appear roughly .2s after the load, so this is fixed?

**Comment by nilmerg** [comment]
Nah, for you it may only be a short delay but this will vary depending on the environment. If there's no reason for this delay (and I can't think of any) these should appear upon initial load.

**Comment by nilmerg** [comment]
Just looked at this. The delay is deliberate. And thinking about a reason again, I guess the environment is the key here. Many badges involve database queries which would fire already upon the initial load without this delay. And on large environments this may be way more than .2 seconds.

So since this is the case for about five years, I'd say we keep it as is.
