### ISSUE TITLE
2.7.X UI broken with Samsung browser

### ISSUE THREAD

**Issue by ThecaTTony** [Icinga/icingaweb2#3924]
The new 2.7.x IcingaWeb2 its broken when browsed in Samsung's smart TV browser's. Things I noticed:
- missing top menu
- broken autorefresh
- dashboard not loading items
- cannot minimize side panel

This issue its present on two smart TV browsers.

![IMG_20190815_164750](https://user-images.githubusercontent.com/6334401/63122818-00b29980-bf7e-11e9-86df-27f4dc484887.jpg)
![IMG_20190815_162601](https://user-images.githubusercontent.com/6334401/63122819-00b29980-bf7e-11e9-9d68-e83dafc1f994.jpg)
![IMG_20190815_162621](https://user-images.githubusercontent.com/6334401/63122820-00b29980-bf7e-11e9-8cfd-ce8a5f92d9bf.jpg)

* Icinga Web 2 version and modules: 2.7.1 (doc generictts monitoring)
* Web browser used:
"Mozilla/5.0 (SMART-TV; Linux; Tizen 2.3) AppleWebkit/538.1 (KHTML, like Gecko) SamsungBrowser/1.0 TV Safari/538.1"
"Mozilla/5.0 (SMART-TV; X11; Linux armv7l) AppleWebkit/537.42 (KHTML, like Gecko) Chromium/25.0.1349.2 Chrome/25.0.1349.2 Safari/537.42"
* Icinga 2 version used: 2.10.5
* PHP version used: 7.3.8
* Server operating system and version: Archlinux fully up to date. nginx 1.16.0.

**Comment by nilmerg** [comment]
Hi,

this looks like the javascript is not correctly loading. This may be due to your server's configuration (it may not answering to web 2's requests) or simply because our javascript is incompatible with the browser used.

Since this is a smart TV browser I'm afraid but we cannot ensure full compatibility here. However, if you are able to provide us a detailed report of what went wrong we may be of help. Unless that's the case, I'll close the issue. Report back if you've got the details.

Best,
Johannes
