### ISSUE TITLE
Implement Director's action hook "inspect" into monitoring module

### ISSUE THREAD

**Issue by m4k5ym** [Icinga/icingaweb2#3986]
Director offers action hook "inspect" which pulls additional informations about running check. This feature is in general very useful for debugging and helps to understand what actually happen.

I'd like to have this feature provided by monitoring module so every can have the benefit.

**Comment by nilmerg** [comment]
Hi,

there are currently no plans to integrate this natively in Icinga Web 2's monitoring module. Partly due to [Icinga DB](https://github.com/Icinga/icingaweb2-module-icingadb) and also due to plans to make the director an integral part of Icinga Web 2. (Just as it's the case for the monitoring module now)
