### ISSUE TITLE
History shows future entries of "Downtime" type

### ISSUE THREAD

**Issue by hardoverflow** [Icinga/icingaweb2#3992]
## Describe the bug
The history of an service shows future entries of type downtime.

## To Reproduce

1. Click on a service that had a future downtime
2. Click on "History"

## Expected behavior
The history shows only events in the past.

## Screenshots
![history_icingaweb2](https://user-images.githubusercontent.com/4113231/68195064-7d21ab00-ffb6-11e9-8cf1-138fc43f3e0b.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version: 2.7.3

**Comment by nilmerg** [comment]
Hi, you're right. The history should only show past events. Though the thing is, it's been this way since a very long time. And since we're currently working on [Icinga DB](https://github.com/Icinga/icingaweb2-module-icingadb) (the successor for the monitoring module) where this is already not the case anymore, I consider this solved.
