### ISSUE TITLE
External logout not working from the navigation dashboard

### ISSUE THREAD

**Issue by Delat0918** [Icinga/icingaweb2#3995]
Hi,
Good day.

I'm a newbie in icinga2. We're trying to setup the icingaweb2 to have an SSO authentication that is integrated in our LDAP. Although we have a successful login using our LDAP accounts, however once we logged out we have this kind of message.
"Logging out...
If this message does not disappear, it might be necessary to quit the current session manually by clearing the cache, or by closing the current browser session."
![icinga issue](https://user-images.githubusercontent.com/38754324/68740104-41758980-0625-11ea-96b2-274c791dc3b0.JPG)

Here is the authentication config file that we have under /etc/icingaweb2/

[root@phwpplabicinga01 icingaweb2]# cat authentication.ini
[icingaweb2]
backend = "db"
resource = "icingaweb_db"

[ldap-user-auth]
backend = "ldap"
resource = "auth-ldap"
user_class = "Person"
user_name_attribute = "uid"
filter = "memberOf=cn=SMT Admins,cn=Roles,dc=vestasext,dc=net"
base_dn = "ou=Users,dc=vestasext,dc=net"

[autologin]
backend = "external"

Here is the icinga2 versions and what we have installed on the icinga2 server:
[root@phwpplabicinga01 icinga2]# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.2-1)

Copyright (c) 2012-2019 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-1062.4.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-LTrJQZ9N-project-322-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

Hoping for your kind advice on this.

Best regards,
Dennis

**Comment by nilmerg** [comment]
Hi,

there should a message appear saying "Logout Successful". You then click the link at the bottom that says "Login" and you should get an authentication prompt.

Which browser is used here? 

And please note that including Icinga 2's version information is not of much help here. The issue template mentions all useful informations, please fill them out instead next time.

**Comment by Delat0918** [comment]
Hi, Johannes.

Thanks for the info , I'll take note of the issue template.

By the way, I have followed your advice. Saw the logout successful, but I have some concerns when loggin out.

When I  click on the User tab and select/click  the logout icon in the upper right side as seen in the image attached it still gives the logging out message.

![icinga_logout](https://user-images.githubusercontent.com/38754324/68824009-712d9b80-06d0-11ea-8fbd-8a15a8b2656f.jpg)

but when I select the the Logout in the bottom left under My account it shows the "Logout Successful" message.
![icinga_logout3](https://user-images.githubusercontent.com/38754324/68824110-b4880a00-06d0-11ea-8ae7-713a1157e420.jpg)

And when I click the Login link it logs me back in and never prompts the "SSO" authentication.

I use a chrome browser for this. we are using the auth_mellon .

Would like to seek for your advice on this, please let me know if you need some further info from my end.

Br, Dennis

**Comment by rtubiera** [comment]
Hi Johannes,

This is to add some comments on Dennis' inquiry  upon checking when we are using the external autologin 

[autologin]
backend = "external"


as per advise by the icinga2 documentation the sso login is working fine, but when we log out again the application it goes to the usual logout of the icinga web (http://10.0.102.171/icingaweb2/authentication/logout) without redirecting to the sso logout.

![image](https://user-images.githubusercontent.com/33832830/68837679-0abc7380-06f8-11ea-8cac-13ed7fcb2248.png)
 and when we try to login again it will redirect automatically to the homepage of my account.
![image](https://user-images.githubusercontent.com/33832830/68837758-3b041200-06f8-11ea-8f85-74f8bf158194.png)

Our goal is when we log-out the application, it will return  back to sso idp login page instead returning to the homepage. 

We got also this error:

[Thu Nov 14 04:10:52.449784 2019] [auth_mellon:error] [pid 9858] [client 10.0.106.34:61781] No known parameters passed to the logout handler. Query string was "(null)". To initiate a logout, you need to pass a "ReturnTo" parameter with a url to the web page the user should be redirected to after a successful logout.
[Thu Nov 14 04:11:05.453509 2019] [auth_mellon:error] [pid 9840] [client 10.0.106.34:61783] Missing required ReturnTo parameter.

What configuration in icingaweb2 do we need to put the "Return to" to  have a successful logout?

also upon checking with the access_log the login page is always redirecting, because it has no successful logout to the sso.
10.0.106.144 - - [14/Nov/2019:00:53:47 -0500] "GET /mellon/login?ReturnTo=http%3A%2F%2F10.0.102.171%2Ficingaweb2%2Fapplication%2Dstate&IdP=http%3A%2F%2Fidp.vestasext.net HTTP/1.1" 303 1287 "http://10.0.102.171/icingaweb2/navigation/dashboard?name=user" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"


I hope you can help us on our issue! Thank you so much

**Comment by nilmerg** [comment]
It's true that initiating the logout from the navigation dashboard doesn't quit the session. This should work the same as the menu entry in the sidebar. <- Bug

Clicking the menu entry works for me. Though, I just got a HTTP basic auth here.

The logout for externally authenticated users in Icinga Web 2 is not really a logout. It just tries to reset the browsers authentication cache. This won't work for all SSO providers.
It's also not configurable in any way. The only chance to properly logout a user authenticated by an SSO provider is to hook into the authentication of Icinga Web 2 with a module.
