### ISSUE TITLE
Enforce positive default limits in user preferences

### ISSUE THREAD

**Issue by K0nne** [Icinga/icingaweb2#4202]
## Is your feature request related to a problem? Please describe.
We have a larger Icinga installation with >90k services. When I try to open `icingaweb2/monitoring/list/services` I get the following error message:

![06-07-_2020_11-40-52](https://user-images.githubusercontent.com/34264690/86585577-f7ac2b80-bf86-11ea-9cef-38772136e562.png)

I just wanted to apply a filter to check the Icinga version on our satellites after our recent update to 2.11.4. To apply the filter I had to open `icingaweb2/monitoring/list/hosts`, apply the filter and change the url from "hosts" to "services" afterwards, because the "Services" menu entry is not working.

## Describe the solution you'd like
After a click on "Services" ("Hosts" is also slightly affected) the GUI should be responsive. Maybe it whould help to limit the examined ci's to a sane number. Another way could be an additional menu entry just for filtering, which shows no ci's at the beginning.

## Describe alternatives you've considered
I open the hosts tab, apply my filter there and change the url afterwards to services.

## Additional context
```
Icinga Web 2 Version
    2.7.3
Git Commit
    06cabfe8ba28cf545a42c92f25484383191a4e51
PHP Version
    7.1.8
Git Commit Datum
    2019-10-18
Copyright
    © 2013-2020 Das Icinga Projekt 
```

**Comment by nilmerg** [comment]
Hi,

this can't be due to the amount of services. The default limit is already set to 25, we're then only counting the remaining services but on the database directly.

It's also a rather enormous amount of memory that's been asked for here. Nearly 340MB.

Did you configure a customized default limit in your preferences with a huge value?

If not, could you please add `?format=sql` to the url and run those queries manually on the database and tell us if there are any anomalies in there? (e.g. Hugely sized text) Though, the IDO schema doesn't have much columns that are bigger than a few bytes. Most other columns are `TEXT` and then only can have 65536 bytes of data.

Does this also happen if you add `?page=20` or even `?page=200` to the url?

**Comment by K0nne** [comment]
I found the source of the problem.  

It was a mistake in my AD-user's config. 
Default page size was defined with **0**. You should prohibit this ;-)
