### ISSUE TITLE
Subgroups on Gui for logically Seperations

### ISSUE THREAD

**Issue by madmax01** [Icinga/icingaweb2#4230]
Hi,

as more Hosts/Services to add,.... it would be really really good able to add an Feature for logically Seperations.

Example:

CustomerXXX
       |
       |-------- WindowsServers
       |-------- LinuxServers
       |--------DBServers

Just example.

this way the gui is not getting messy,.... right now just to have a flat line vertically is very messy.

that would be a very good  way.

thx

**Comment by 0xliam** [comment]
I would also love to see something like this - we migrated from PRTG to Icinga2 and my colleagues are used to dealing with PRTG's "tree" view, which is separated by the PRTG equivalent of a satellite (and can have nested groups).

We have ~2000 hosts and will be adding another ~400 servers and ~300 network devices, so our interface as become rather difficult to navigate.

**Comment by nilmerg** [comment]
Hi,

have you already taken a look at [Icinga Business Process Modelling](https://github.com/Icinga/icingaweb2-module-businessprocess) and [Icinga Cube](https://github.com/Icinga/icingaweb2-module-cube)? These might already solve your needs.

Because of that, I'd also have to add, that adding an overview structured this way directly to Icinga Web 2 is nothing we have planned nor intend to do so.

**Comment by nilmerg** [comment]
I think I've provided two very suitable alternatives. We also don't intend to add such a *tree* view to Icinga Web 2 due to this.
