### ISSUE TITLE
Service Grid - Hide Acknowledged Problems

### ISSUE THREAD

**Issue by bmccorkle** [Icinga/icingaweb2#4261]
## Is your feature request related to a problem? Please describe.
It appears that the service grid shows even acknowledged problems.  Some of the equipment we monitor is controlled by other departments.  It would be nice to be able to acknowledge problems and hide on the service grid.

## Describe the solution you'd like
An option to only display problems that have not been acknowledged

**Comment by nilmerg** [comment]
Hi,

the default view *"Problems Only"* is a special filter which only excludes services where all occurrences are *OK*. This is by design, as the service grid is meant as a global overview, and there it's also of interest to see handled problems.

If you don't like to see handled problems though, you're free to add another filter which excludes them.

**Comment by bmccorkle** [comment]
Thanks nilmerg.  Some of the other departments drag out resolving issues.  My fault for not taking more time to look at the filter options.
