### ISSUE TITLE
Permission: Host without service filtered by service_description

### ISSUE THREAD

**Issue by sklaes** [Icinga/icingaweb2#4308]
## Describe the bug
Hosts wich do not have any services are filtered out as soon as a filter on service_description is set in the role.

## To Reproduce

1. Create a host with **no[!]** services attached
2. Create a role with "monitoring/​filter/​objects" set to something like this: "service_description=customer*"
3. Assign a user to that role
4. Log in as the recently created user
5. Try to view the the host created in step one.

## Expected behavior
Host should be visable

## Screenshots
Without service_description filter:
![image](https://user-images.githubusercontent.com/13706940/105996820-23ba0600-60ab-11eb-9beb-e4d456ad3361.png)

With service_description filter (same host):
![image](https://user-images.githubusercontent.com/13706940/105997181-988d4000-60ab-11eb-82f5-a6e83eaac4be.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.8.2 (8a89839af94a247ee2149b2336c73b8251b477c0)
* Web browser used: Edge 88
* Icinga 2 version used (`icinga2 --version`): 2.12.3
* PHP version used (`php --version`):  7.3.20
* Server operating system and version: Centos 7

**Comment by nilmerg** [comment]
Hi sklaes!

I really understand why you have an issue with this behavior of this restriction. Though, this restriction is applied to all objects after all and your filter requires a specific service that is related to an object (be it a host or a group) to show up. This behavior won't change and is exactly the same as with #3962. (also reported by you :wink: )

So I'd close here in favor of #3550. Though, please note that the work-around mentioned there does not apply here because a host without service can't be found as well with a service customvar being used instead.

But rest assured, I'm currently working at exactly this feature but for Icinga DB Web. So that this will work for the initial release of it right away. :vulcan_salute:

**Comment by sklaes** [comment]
Hey @nilmerg,
thanks for your reply, i am glad that that this will work on Icinga DB Web.
I already forgot that my first intention was to resolve the (same) problem with a service group :-D
