### ISSUE TITLE
View port glitch in Chrome when Configuring Role Permission

### ISSUE THREAD

**Issue by mdetrano** [Icinga/icingaweb2#4310]
## Describe the bug
When editing a Role and its module permissions in Chrome, the display will shift, sometimes go blank, after clicking on certain toggle buttons to enable/disable a permission setting.  Appears that the viewport is shifted up and out of the window itself.  Issue is not present in Firefox.  Observed on Linux and Mac systems.

# To Reproduce
Go into configuration , Authentication, and add a new role.  In the Update Role tab, expand the modules and scroll down (buttons near the top don't seem to cause the glitch), and click on a toggle button (like General Module Access for the Translation module).  The display is corrupted upon clicking the control

## Expected behavior
The form should stay put when clicking toggle slider controls.

## Screenshots
![image](https://user-images.githubusercontent.com/20076416/106215142-e8e0cc80-6195-11eb-9641-2a97a760c870.png)

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.8.2
* Web browser used: Chrome (also saw in Chromium, and Konqueror...might be webkit based browsers in general)
* Icinga 2 version used (`icinga2 --version`):
* PHP version used (`php --version`): 7.3
* Server operating system and version: Centos Linux 8

## Additional context
Issue not present in Firefox browser.  If the view disappears in Chrome, can restore by zooming out, then zooming back in on the browser.  Tried this on a stripped down, bare-bones Web2 setup (no other modules but the ones packaged, default theme).

**Comment by mdetrano** [comment]
Problem has also been observed when using the same style "toggle-slider" buttons to modify an object settings, like "acivate host checks" in the host detail pane, on Chrome.

**Comment by lippserd** [comment]
ref/IP/33375

**Comment by flourish86** [comment]
Should be fixed with 7ce3997.

And so should #4193 be.

**Comment by nilmerg** [comment]
`position: fixed`? :fearful: That feels like shooting with cannons upon pigeons. Could you explain please why this is the solution, what's caused it and maybe a source?

**Comment by flourish86** [comment]
When an input, that is out of view in a container with overflow is focussed, Browsers scroll to the according element, so that becomes visible to the user.

When you click an interactive element, it is set `focus` state. In our case this happens to the checkbox input, which is part of the toggle.

There seems to be a problem with this in Chrome, if the topmost (DOM hierarchy-wise) is set to `display: flex`. In our case the `#layout` container. Having it not set to `display: flex` fixes this.

I don't have any sources other than excessive trial and error and this is the solution that seems to work and doesn't seem to break anything.

You can recreate the issue also, by focussing the input via js. $('#the-id-of-the-input-element').focus().

**Comment by nilmerg** [comment]
Okay, but trial and error isn't a valid reason to introduce a `position` instruction again on our layout. I highly discourage that.

Tried it on my own now based on your explanation, and figured it has to do something with how we hide the native checkbox for our own. Removing the `sr-only` class from the input doesn't produce this issue. I suppose we have to hide the input somehow else in order to avoid this viewport glitch. Please try something in this regard instead.

**Comment by flourish86** [comment]
> Tried it on my own now based on your explanation, and figured it has to do something with how we hide the native checkbox for our own. Removing the `sr-only` class from the input doesn't produce this issue. I suppose we have to hide the input somehow else in order to avoid this viewport glitch. Please try something in this regard instead.

Clever. I will.

**Comment by flourish86** [comment]
We could just set the input to `visibility: hidden` or `display: none`, which works layout and function-wise.

But according to [this](https://stackoverflow.com/questions/1755656/displaynone-vs-visibilityhidden-vs-text-indent9999-how-screen-reader-behave-w) most screen readers will ignore the element then.

I couldn't find a different method to make both work.

**Comment by nilmerg** [comment]
According to https://webaim.org/techniques/css/invisiblecontent/ and https://caniuse.com/?search=hidden we could use `<input type="checkbox" hidden ... />`. Just tried it and it works fine out-of-the-box. (In chrome)
