### ISSUE TITLE
Sorting of services by long output

### ISSUE THREAD

**Issue by samuraiii** [Icinga/icingaweb2#4313]
Hi,
I would like to request a new feature:
Possibility of sorting of services by their long output.
for example in path
`icingaweb2/monitoring/list/services`
It is especially useful for checks which return some kind of time information (certificate validity left...)
Thank you fro great work
S

**Comment by nilmerg** [comment]
Hi,

we won't add this explicitly because of the performance implications regarding the IDO (the database). Sorting based on large TEXT columns (which `long_output` is) will lead to very poor performance in large environments. You should consider filtering for the results you're interested in, and not using the sort functionality for that.
