### ISSUE TITLE
login page keeps on redirecting to itself. login is failing. 

### ISSUE THREAD

**Issue by passaf** [Icinga/icingaweb2#4316]
Hello, I am unable to login to the icingaweb2 console. 
If I put wrong credentials it gives wrong credentials but if they are correct it just refresh/redirect to the same page. 
I tried the below steps but the issue wasn't solved : 
1-Reboot the server and the services accordingly 
2-Set Selinux to permissive, checked all the permissions 
3-Uninstalll and install again incingaweb2 
4-Reset the password , create a new user 
5-Checked all the resources

P.S : the service is running and I am receiving alerts when a service is down. so only the login is failing . 

And one another important note is that I am always getting the following error when opening the login page after closing the firefox : "Cookies must be enabled to run this application. " (getting this error from three different laptops ) I am doing a  workaround for this issue ,I have 2 icinga instances running on the same private IP but in different networks on azure. so I open the console using the second instance network and when it opens , I switch backu to the first network and refresh the page and here comes the login issue again. I believe it may be related .

**Comment by nilmerg** [comment]
Hi,

to me this smells like an issue with your session storage. (i.e. an issue with your setup)

We're handling only bugs/features here. Since we have no other reports like this, I won't mark this as bug yet. Please head over to our [forums](https://community.icinga.com/) where other users can also be of help. (I'm also active there and reading by) If your issue is then indeed identified as bug, please re-open here and add all the required details. 

Thanks,
Johannes
