### ISSUE TITLE
Safari and Firefox: Tab key does not work properly

### ISSUE THREAD

**Issue by sukhwinder33445** [Icinga/icingaweb2#4412]
## Describe the bug
Changing the focus of a form element by pressing the tab key does not work properly.
* Tab key ignore the Login button on the login page and ignore submit buttons (Safari).
* Tab key ignore main menu items and page tabs (Safari and Firefox).

To reproduce:
Go to any form page (e.g preferences, login page) and try to move over the form element with tab key.

**Comment by flourish86** [comment]
This is working by design in Safari. The user can solve this by checking the following option in Safari > Preferences.

![Screen Shot 2021-07-05 at 10 16 37](https://user-images.githubusercontent.com/6977434/124440150-9b870d80-dd7a-11eb-96e8-9eb6ac3bf6d9.png)

For Firefox, this may have changed recently. Since it works on Ubuntu, I think it's by design as well, as there's a global macOS option for this. Ticking the following check box will solve it.

![Screen Shot 2021-07-05 at 10 16 37](https://user-images.githubusercontent.com/6977434/124440346-d2f5ba00-dd7a-11eb-8b38-f14c0ad40c83.png)

**Comment by sukhwinder33445** [comment]
Thank you. 
I enabled the option in `Safari > Preferences` as you showed above. Now, Safari works fine 🥳 , but Firefox still has the issue.

**Comment by nilmerg** [comment]
> but Firefox still has the issue.

Please check again with the latest master. Works fine for me with Firefox on Ubuntu.

**Comment by Yonas-net** [comment]
> but Firefox still has the issue.

Can also confirm this. Even with the current master still doesn't work.

**Comment by nilmerg** [comment]
Then this is a Firefox on MacOS issue, not ours. I can't investigate this. Anyone here, please do this by yourself.

**Comment by flourish86** [comment]
> For Firefox, this may have changed recently. Since it works on Ubuntu, I think it's by design as well, as there's a global macOS option for this. Ticking the following check box will solve it.
> 
> ![Screen Shot 2021-07-05 at 16 36 38](https://user-images.githubusercontent.com/6977434/124487645-431e3300-ddaf-11eb-9dec-355dd0204854.png)

Sorry, the second screen was the same as the first. You have to check the global option in macOS for making Firefox work. See updated comment.

**Comment by Yonas-net** [comment]
Unfortunately, I don't see any change at all whereas this option is checked or unchecked. Is still like before.
