### ISSUE TITLE
Make formatting of dates/times/numbers configurable independently of the chosen locale

### ISSUE THREAD

**Issue by fkusei** [Icinga/icingaweb2#4465]
The date picker seems to get its date format from the selected browser locale. This results in all users wanting to use icingaweb in english have to use MM/DD/YYYY format. Please add an option to revert this back to ISO date format (YYYY-MM-DD).

![screenshot](https://user-images.githubusercontent.com/60259101/126320241-05a88f72-9d00-49b2-a961-11970a980e18.png)

**Comment by nilmerg** [comment]
I'm afraid, but one of the core features of the new datetime picker is the locale aware formatting. It uses the common date and time format of the currently selected locale. In your case it's the english locale so you get MM/DD/YYYY and AM/PM (instead of 24 hours).

The ISO date format is not intended for human interaction and has the disadvantage that not-so technical users are not familiar with it. The change was made to improve the user experience and I think reverting this back to the ISO format is the wrong direction.

Instead I'd like to know, what your problem with the locale aware formatting is? Is this just a matter of getting accustomed to the new format? Do you miss the ability to paste a copied string? (See #4442)

**Comment by fkusei** [comment]
My exact problem is "My browser uses `en_DK`, but icingaweb uses `en_US` for date formatting, which is wrong". Also, not all english-speaking people use the american date and time format.

**Comment by nilmerg** [comment]
I didn't knew that `en_DK` is even a thing. And the more I read up on it, the less I think of it as a valid locale. It's more of an ancient work-around that no modern software has to support. But I understand the reason why it has been *invented*.

We make the timezone configurable, because someone working in Europe (or working in the USA for some European company) may want to see dates according to the local/target timezone. Why shouldn't we also support to choose the formatting of dates, times, numbers and such independently from the locale? Ubuntu also allows it, and I even use it. :sweat_smile:

**Comment by fkusei** [comment]
> We make the timezone configurable, because someone working in Europe (or working in the USA for some European company) may want to see dates according to the local/target timezone. Why shouldn't we also support to choose the formatting of dates, times, numbers and such independently from the locale?

That's exactly what I wanted to say in the first post :)

(For reference, i noticed my browser actually uses `en_GB`, because (surprise!) Firefox does not support `en_DK`.)

**Comment by nilmerg** [comment]
Since [we're not using the new datetime picker for e.g. Chrome anymore](https://github.com/Icinga/icingaweb2/issues/4442#issuecomment-887292216), but the native widget, we cannot implement this I'm afraid. It's now under the control of Chrome which format is used. We also can't promise to add this to Firefox, because we aren't sure if the new datetime picker will be kept even there.

Since the different format for datetime inputs is now off the table and this was the initial requirement for this issue, I'll close here.
