### ISSUE TITLE
Documentation: Upgrade Icingaweb2 to 2.9.0 is wrong / confusing

### ISSUE THREAD

**Issue by winter1967** [Icinga/icingaweb2#4482]
## Describe the bug
In https://github.com/Icinga/icingaweb2/blob/master/doc/80-Upgrading.md ist described:
```
Upgrading to Icinga Web 2 2.9.x
Installation
Icinga Web 2 now requires the Icinga PHP Library (ipl) (>= 0.6) and Icinga PHP Thirdparty (>= 0.10). Please make sure to install both when upgrading.
 We provide packages for them and if you've installed Icinga Web 2 already by package they should be installed automatically during the upgrade.

```
In fact, IcingaPHP Thirdparty exists, but it's not usable and not needed, because it contains only two shell-scripts and a "composer.json" which is the same as in /usr/share/icinga-php/vendor after upgrade to Icingaweb 2.9.0

Btw:
When you want to prepare the upgrade, you don't find the path /usr/share/icinga-php, it exists AFTER Installation of icingaweb2.
Normally, i take a look in the upgrade doku, upgrade what i need for the new package (here icingaweb2) and upgrade the package.

Not at all.. the instruction of the thirdparty module is confusing., don't know were to install
/usr/share/icinga-php/vendor
/usr/share/icinga-php/vendor/vendor?

## To Reproduce
Read the documentation: https://github.com/Icinga/icingaweb2/blob/master/doc/80-Upgrading.md

## Expected behavior
I would expect, that the documentation is valid and correct, i heared, that the third party modul will replace ipl and reactbundle, but not at all in the documentation and.. the thirdparty modul is not usable.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.9.0

**Comment by lippserd** [comment]
You already quoted the docs:

> We provide packages for them and if you've installed Icinga Web 2 already by package they should be installed automatically during the upgrade.

You don't have to install the dependencies yourself as they're already installed when upgrading the `icingaweb2` package.

Is it just the word `should` that bothers you?

**Comment by winter1967** [comment]
IPL in Version >=0.6.0 has not been installed with the icinga2 package (i take a look in the modules of icingaweb2 and 0.5.0 is still installed), our netways support don't know an answer why the documentations sounds so.
Better:
In the new package of icingaweb2, the modules ipl and .. reactos??? is included and have not to be installed.. 

but why, there's still the version of IPL in the old Version?
Or should i remove the IPL (old) and the IPL (new) is in icingaweb2 included but not visable as a module?

**Comment by nilmerg** [comment]
> In fact, IcingaPHP Thirdparty exists, but it's not usable and not needed, because it contains only two shell-scripts and a "composer.json" which is the same as in /usr/share/icinga-php/vendor after upgrade to Icingaweb 2.9.0

You say `/usr/share/icinga-php/vendor/vendor` does not exist after the upgrade to v2.9 but `/usr/share/icinga-php/vendor` does? Please tell us your distribution and from which version you've upgraded from.

> Btw:
> When you want to prepare the upgrade, you don't find the path /usr/share/icinga-php, it exists AFTER Installation of icingaweb2.
> Normally, i take a look in the upgrade doku, upgrade what i need for the new package (here icingaweb2) and upgrade the package.

Nice that you check the upgrading documentation *first*! :+1: Recently many users in our support channels didn't. :neutral_face: (seemingly)
The upgrade documentation tells you that these are packages that get automatically installed. The same tells you the README.md on each repository. Why do you think you have to install them manually?

> i heared, that the third party modul will replace ipl and reactbundle, but not at all in the documentation

`icinga-php-library` replaces the `icingaweb2-module-ipl`. `icinga-php-thirdparty` replaces the `icingaweb2-module-reactbundle`. Also mentioned in the respective repository [here](https://github.com/Icinga/icingaweb2-module-ipl) and [here](https://github.com/Icinga/icingaweb2-module-reactbundle). There's no need to refer to the old modules in the new repositories, as they are **deprecated** and shouldn't be used without an explicit requirement.

> IPL in Version >=0.6.0 has not been installed with the icinga2 package (i take a look in the modules of icingaweb2 and 0.5.0 is still installed), our netways support don't know an answer why the documentations sounds so.

The documentation doesn't mention that these are modules anywhere. It uses the term `library`. Take a look at the about page of Icinga Web 2, there you'll see the installed libraries as well as the modules. `icinga-php-library` and `icinga-php-thirdparty` should appear there after the upgrade to v2.9.

> but why, there's still the version of IPL in the old Version?

Because you've installed it manually. Packages cannot remove something they didn't create in the first place. You *can* remove it, as long as you're not still using the Director in version 1.8.0 or lower. (Also stated in the deprecation notice of each module)

**Comment by nilmerg** [comment]
Since there's no further feedback and I described the current situation above, I consider this solved.
