### ISSUE TITLE
Custom vars not resolved in UI

### ISSUE THREAD

**Issue by fl0wx** [Icinga/icingaweb2#4666]
## Describe the bug
Hey i expect to see resolved variables references if i use them in my configuration. I configured all objects via Director 1.8.0.

## Expected behavior
I expect to see resolved variables in the UI

## Screenshots
![image](https://user-images.githubusercontent.com/2448081/153208464-0f011e03-ac68-47d8-88d9-582f49cf6847.png)
## Your Environment

* Icinga Web 2 version and modules (System - About): 2.9.5
* Version used (`icinga2 --version`): 2.11.3
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Config validation (`icinga2 daemon -C`):

**Comment by nilmerg** [comment]
Hi,

icingaweb2 (the monitoring module) cannot resolve the same macros that Icinga 2 can. We also don't plan to add support for that since Icinga DB Web already does. So the only thing we might do, is resolve macros in custom variables as part of Icinga DB Web. If you're interested in this, please create an issue [over there](https://github.com/Icinga/icingadb-web/issues).
