### ISSUE TITLE
The filter column `host_next_update` is not allowed here.

### ISSUE THREAD

**Issue by yhabteab** [Icinga/icingaweb2#4797]
## Describe the bug
The url filters provided by the monitoring module don’t work anymore since this change 8898ed85ab6136e8f7b31da3c99d699ca113a7ca. To be precise, this is due to the change from `FilterMatch` to `FilterExpression` in `DataView::validateFilterColumns()`.

https://github.com/Icinga/icingaweb2/blob/777d146ba146b00e29f334f93de567dc491fbf28/modules/monitoring/library/Monitoring/DataView/DataView.php#L459-L460

<img width="832" alt="Bildschirmfoto 2022-05-30 um 09 43 51" src="https://user-images.githubusercontent.com/57616252/170942692-c86fc987-bc37-49d2-bbb6-8a4e700fb490.png">

**Comment by nilmerg** [comment]
That's due to the columns being missing their related data views. (`host_next_update` -> `HostStatus`, `service_next_update` -> `ServiceStatus`.

They are available in the respective query (e.g. `HostStatusQuery`). Registering them in the data views solves the issue.

Though, I suspect more cases as the columns definition in both views might further deviate from those of the respective query.
