### ISSUE TITLE
Fatal error: Uncaught Error: Class 'ipl\I18n\GettextTranslator' not found in

### ISSUE THREAD

**Issue by slaser1274** [Icinga/icingaweb2#4802]
hi,
i have icingaweb2 version 2.8.2 running, when i try to update to 2.10.1 i get the following error.

Fatal error: Uncaught Error: Class 'ipl\I18n\GettextTranslator' not found in ....

i cloned the ipl repo to icingaweb2/modules/ipl and also the repo Icinga PHP Thirdparty to icingaweb2/vendor. 

despite all this i still get the above error.

**Comment by nilmerg** [comment]
You seem to be not using packages. Otherwise the dependencies would fulfill these requirements.

You have to install https://github.com/Icinga/icinga-php-library and https://github.com/Icinga/icinga-php-thirdparty. But note: These are **not** modules, check the installation instructions thouroughly!

**Comment by slaser1274** [comment]
I had also tried php-libray to icingaweb2 and php-thirdparty to icingaweb2/vendor/icinga-php-thirdparty, unfortunately the same error keeps coming.  What am I doing wrong?

**Comment by lippserd** [comment]
I meant to install a package via yum, dnf, zypper, apt or whatever OS you’re running: https://icinga.com/docs/icinga-web-2/latest/doc/02-Installation/#installation

**Comment by slaser1274** [comment]
Thank´s it´s works

**Comment by lippserd** [comment]
> Thank´s it´s works

You're welcome!
