### ISSUE TITLE
Icinga/User->can() function matches wrong permission

### ISSUE THREAD

**Issue by gianlucapiccolo** [Icinga/icingaweb2#4829]
## Describe the bug
A user "joe" belongs to the role "editor". The role "editor" contains the permission for the module "blog". The blog module provides the following permissions: 
- blog/admin
- blog/editor
- blog/viewer

The role "editor" has the following configuration:
```
[editor]
users = "joe"
permissions = "module/blog,blog/editor"
```
In the blog module the code checks if the logged user has "Full module access" enabled but the following function acts in an apparently wrong behavior: 
```$user->can('blog/*'); // returns true ($user is an Icinga/User class instance)```

## To Reproduce
1. Unzip the module [blog.zip](https://github.com/Icinga/icingaweb2/files/8958571/blog.zip)
2. Copy the `blog` folder in the Icinga Web 2 modules dir
3. `icingacli module enable blog`
4. Create user `joe`
5. Create role `editor`, assign to it the `joe` user, enable the `module/blog` (General module access) and the `blog/editor` permissions
6. Log into Icinga Web 2 with user `joe`
7. Access the blog module

## Expected behavior
The function should return `false` since the user has only the "General module access" and the "blog/editor" permission, not the "Full module access".

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.10.1
* PHP version used (`php --version`): 7.4.6

**Comment by nilmerg** [comment]
Hi,

this works as intended.

But I see why you think it does not.

The thing is, a role grants permissions, so it has the capability to grant an entire set of permissions with a single rule. (`monitoring/command/*`) This avoids the need to list all individual permissions.

The program (Icinga Web 2, a module) requires permissions. In contrast to the role however, it only requires a single permission at at time for a given action. There's no point in requiring an entire set of permissions, as then it wouldn't make sense to provide them individually in the first place. If such a permission is wanted, a single permission should be used in multiple places for multiple actions instead.

The current behavior of `User::can()` allows the program to express the following question: *Is any permission in this set granted?* (`blog/*` thus matches `blog/viewer`, `blog/editor` or `blog/admin`)

The examples I've used here are from your example module. There it's already obvious that the usage of the `blog/*` permission is questionable because you have a `blog/admin` permission. Why should a `blog/admin` need `blog/viewer` or `blog/editor` in addition?

The current mechanics are also already in use elsewhere. Changing it is a breaking change and I don't see a justification in the example module for such a change.
